export const restList = [
 
    {
        id: "1",
        name: "Amigoo Noshery",
        dbname: "amigo",
        type: "veg",
        place: "Venkata Ramana Colony",
        lat: 15.8345085, // Hard-coded Latitude
        lng: 78.029391, // Hard-coded Longitude
        rating: "4.2",
        image: "/2.jpg",
    },
    {
        id: "2",
        name: "Viva Finedine",
        dbname: "viva",
        type: "Non-veg",
        place: "Nandyal Road",
        lat: 15.7796123,
        lng: 78.0566811,
        rating: "4.1",
        image: "/pv.jpg",
    },
    {
        id: "3",
        name: "Mr.Hangout Café",
        dbname: "Mr.Hangout Café",
        type: "non-veg",
        place: "Venkata Ramana Colony",
        lat: 15.842579,
        lng: 78.0316344,
        rating: "4.5",
        image: "/snow.jpg",
    },
    {
        id: "4",
        name: "Reddy Family Restuarent",
        dbname: "Reddy Family Restuarent",
        type: "non-veg",
        place: "Venkata Ramana Colony",
        lat: 15.7773726,
        lng: 78.0574997,
        rating: "4.5",
        image: "/snow.jpg",
    },
    {
        id: "5",
        name: "Aaha Kitchens",
        dbname: "Aaha Kitchens",
        type: "non-veg",
        place: "Venkata Ramana Colony",
        lat: 15.7869693,
        lng: 78.0336955,
        rating: "4.5",
        image: "/snow.jpg",
    },

    {
        id: "6",
        name: "The Bro Story",
        dbname: "The Bro Story",
        type: "non-veg",
        place: "Venkata Ramana Colony",
        lat: 15.8061675,
        lng: 78.0477926,
        rating: "4.5",
        image: "/snow.jpg",
    },
    {
        id: "7",
        name: "Fun and Food",
        dbname: "Fun and Food",
        type: "non-veg",
        place: "Venkata Ramana Colony",
        lat: 15.8238195,
        lng: 78.0370324,
        rating: "4.5",
        image: "/snow.jpg",
    },
    {
        id: "8",
        name: "PR Grand",
        dbname: "PR Grand",
        type: "non-veg",
        place: "Venkata Ramana Colony",
        lat: 15.8355764,
        lng: 78.0174753,
        rating: "4.5",
        image: "/snow.jpg",
    },
    {
        id: "9",
        name: "Food Land",
        dbname: "Food Land",
        type: "non-veg",
        place: "Venkata Ramana Colony",
        lat: 15.7958589,
        lng: 78.0605149,
        rating: "4.5",
        image: "/snow.jpg",
    },
    {
        id: "10",
        name: "Talimpu Family Restaurant",
        dbname: "Talimpu Family Restaurant",
        type: "non-veg",
        place: "Venkata Ramana Colony",
        lat: 15.7888614,
        lng: 78.0540306,
        rating: "4.5",
        image: "/snow.jpg",
    },
    {
        id: "11",
        name: "Hotel Taj Darbar",
        dbname: "Hotel Taj Darbar",
        type: "non-veg",
        place: "Venkata Ramana Colony",
        lat: 15.8255741,
        lng: 78.0340477,
        rating: "4.5",
        image: "/snow.jpg",
    },
     {
        id: "12",
        name: "Ruchivedhika",
        dbname: "Ruchivedhika",
        type: "non-veg",
        place: "Venkata Ramana Colony",
        lat: 15.8245927,
        lng: 78.0195797,
        rating: "4.5",
        image: "/snow.jpg",
    },
    {
        id: "13",
        name: "Hindustan Hotel",
        dbname: "Hindustan Hotel",
        type: "non-veg",
        place: "Venkata Ramana Colony",
        lat: 15.8312209,
        lng: 78.0447529,
        rating: "4.5",
        image: "/snow.jpg",
    },
    {
        id: "14",
        name: "LASSI CORNER",
        dbname: "LASSI CORNER",
        type: "non-veg",
        place: "Venkata Ramana Colony",
        lat: 15.7966878,
        lng: 76.9620473,
        rating: "4.5",
        image: "/snow.jpg",
    },
    {
        id: "15",
        name: "Mandi@9R",
        dbname: "Mandi@9R",
        type: "non-veg",
        place: "Venkata Ramana Colony",
        lat: 15.8308853,
        lng: 78.0446194,
        rating: "4.5",
        image: "/snow.jpg",
    }
]