export const Data = [

    //lassi corrner
    //lassi corner
    // Lassi
    { id: 1652, name: "Sweet Lassi", price: 50, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Lassi" },
    { id: 1653, name: "Jaljeera Lassi", price: 50, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Lassi" },
    { id: 1654, name: "Roohafza Lassi", price: 60, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Lassi" },
    { id: 1655, name: "Strawberry Lassi", price: 70, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Lassi" },
    { id: 1656, name: "Mango Lassi", price: 70, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Lassi" },
    { id: 1657, name: "Mango Banana Lassi", price: 80, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Lassi" },
    { id: 1658, name: "Pineapple Lassi", price: 80, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Lassi" },
    { id: 1659, name: "Chocolate Lassi", price: 80, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Lassi" },
    { id: 1660, name: "Fruit Lassi", price: 90, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Lassi" },
    { id: 1661, name: "Butterscotch Lassi", price: 90, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Lassi" },
    { id: 1662, name: "Blackcurrant Lassi", price: 90, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Lassi" },
    { id: 1663, name: "Kesar Badam Lassi", price: 90, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Lassi" },
    { id: 1664, name: "Pista Lassi", price: 90, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Lassi" },
    { id: 1665, name: "Blueberry Lassi", price: 90, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Lassi" },
    { id: 1666, name: "Dryfruit Lassi", price: 100, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Lassi" },
    // Mocktail
    { id: 1667, name: "Lime Mocktail", price: 80, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Mocktail" },
    { id: 1668, name: "Original Mocktail", price: 90, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Mocktail" },
    { id: 1669, name: "Strawberry Mocktail", price: 90, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Mocktail" },
    { id: 1670, name: "Roohafza Mocktail", price: 90, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Mocktail" },
    { id: 1671, name: "Mint & Lime Mocktail", price: 100, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Mocktail" },
    { id: 1672, name: "Mint Masala Mocktail", price: 100, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Mocktail" },
    { id: 1673, name: "Granadine Mocktail", price: 100, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Mocktail" },
    { id: 1674, name: "Mango Mocktail", price: 100, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Mocktail" },
    { id: 1675, name: "Espresso Mocktail", price: 110, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Mocktail" },
    { id: 1676, name: "Blueberry Mocktail", price: 110, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Mocktail" },
    { id: 1677, name: "Green Apple Mocktail", price: 120, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Mocktail" },
    { id: 1678, name: "Blue Coraco Mocktail", price: 120, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Mocktail" },
    { id: 1679, name: "Watermelon Mocktail", price: 120, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Mocktail" },
    { id: 1680, name: "Raspberry Mocktail", price: 120, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Mocktail" },
    // MILK SHAKES
    { id: 1681, name: "Rose Milk Shake", price: 70, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Milk Shakes" },
    { id: 1682, name: "Vanilla Shake", price: 70, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Milk Shakes" },
    { id: 1683, name: "Oreo Shake", price: 80, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Milk Shakes" },
    { id: 1684, name: "Strawberry Shake", price: 80, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Milk Shakes" },
    { id: 1685, name: "Snickers Shake", price: 80, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Milk Shakes" },
    { id: 1686, name: "Blackcurrant Shake", price: 90, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Milk Shakes" },
    { id: 1687, name: "Kitkat Shake", price: 90, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Milk Shakes" },
    { id: 1688, name: "Mango Shake", price: 90, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Milk Shakes" },
    { id: 1689, name: "Belgium Chocolate Shake", price: 90, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Milk Shakes" },
    { id: 1690, name: "Green Pista Shake", price: 90, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Milk Shakes" },
    { id: 1691, name: "Butterscotch Shake", price: 90, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Milk Shakes" },
    { id: 1692, name: "Kesar Badam Shake", price: 90, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Milk Shakes" },
    { id: 1693, name: "Mango Strawberry Shake", price: 100, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Milk Shakes" },
    { id: 1694, name: "Kiwi Smoothie Shake", price: 100, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Milk Shakes" },
    { id: 1695, name: "Ferrero Rocher Shake", price: 100, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Milk Shakes" },
    { id: 1696, name: "Cake Mud Shake", price: 100, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Milk Shakes" },
    { id: 1697, name: "Dryfruit Shake", price: 100, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Milk Shakes" },
    { id: 1698, name: "Vanilla Apple Berg Shake", price: 100, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Milk Shakes" },
    { id: 1699, name: "Choco Scotch Shake", price: 100, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Milk Shakes" },
    { id: 1700, name: "Belgium Chips Shake", price: 100, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Milk Shakes" },
    { id: 1701, name: "Blueberry Smoothie Shake", price: 100, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Milk Shakes" },
    { id: 1702, name: "Nutella Shake", price: 110, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Milk Shakes" },
    { id: 1703, name: "Avacado Strawberry Shake", price: 110, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Milk Shakes" },
    { id: 1704, name: "Lychee Mango Shake", price: 110, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Milk Shakes" },
    { id: 1705, name: "Protein Shake", price: 110, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Milk Shakes" },
    // THICK SHAKES
    { id: 1706, name: "Vanilla Thickshake", price: 100, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Thick Shakes" },
    { id: 1707, name: "Chocolate Thickshake", price: 120, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Thick Shakes" },
    { id: 1708, name: "Strawberry Thickshake", price: 120, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Thick Shakes" },
    { id: 1709, name: "Mango Thickshake", price: 130, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Thick Shakes" },
    { id: 1710, name: "Pineapple Thickshake", price: 130, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Thick Shakes" },
    { id: 1711, name: "Mango Strawberry Thickshake", price: 140, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Thick Shakes" },
    { id: 1712, name: "Pista Thickshake", price: 140, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Thick Shakes" },
    { id: 1713, name: "Butterscotch Thickshake", price: 140, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Thick Shakes" },
    { id: 1714, name: "Blackcurrant Thickshake", price: 150, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Thick Shakes" },
    // ICE CREAM SHAKES
    { id: 1715, name: "Vanilla Ice Cream Shake", price: 90, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Ice Cream Shakes" },
    { id: 1716, name: "Strawberry Ice Cream Shake", price: 110, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Ice Cream Shakes" },
    { id: 1717, name: "Mango Ice Cream Shake", price: 120, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Ice Cream Shakes" },
    { id: 1718, name: "Chocolate Ice Cream Shake", price: 120, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Ice Cream Shakes" },
    { id: 1719, name: "Pineapple Ice Cream Shake", price: 130, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Ice Cream Shakes" },
    { id: 1720, name: "Pista Ice Cream Shake", price: 130, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Ice Cream Shakes" },
    { id: 1721, name: "Butterscotch Ice Cream Shake", price: 130, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Ice Cream Shakes" },
    { id: 1722, name: "Coffee Ice Cream Shake", price: 130, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Ice Cream Shakes" },
    { id: 1723, name: "Mango Strawberry Ice Cream Shake", price: 140, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Ice Cream Shakes" },
    { id: 1724, name: "Dryfruit Ice Cream Shake", price: 150, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Ice Cream Shakes" },
    { id: 1725, name: "Chocoscotch Ice Cream Shake", price: 150, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Ice Cream Shakes" },
    { id: 1726, name: "Blackcurrant Ice Cream Shake", price: 150, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Ice Cream Shakes" },
    // COLD COFFEES
    { id: 1727, name: "Rock Island", price: 70, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Cold Coffees" },
    { id: 1728, name: "Coffee Italia", price: 80, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Cold Coffees" },
    { id: 1729, name: "Boost", price: 80, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Cold Coffees" },
    { id: 1730, name: "Horlicks", price: 80, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Cold Coffees" },
    { id: 1731, name: "Complain", price: 80, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Cold Coffees" },
    { id: 1732, name: "Bournvita", price: 80, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Cold Coffees" },
    { id: 1733, name: "Kitkat Coffee", price: 90, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Cold Coffees" },
    { id: 1734, name: "8PM Coffee", price: 90, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Cold Coffees" },
    { id: 1735, name: "Chaco Coffee", price: 90, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Cold Coffees" },
    { id: 1736, name: "Coffee with Cake", price: 100, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Cold Coffees" },
    { id: 1737, name: "Nutella Coffee", price: 110, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Cold Coffees" },
    // BANANA BONKERS
    { id: 1738, name: "Vanilla Banana", price: 80, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Banana Bonkers" },
    { id: 1739, name: "Chocolate Banana", price: 90, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Banana Bonkers" },
    { id: 1740, name: "Strawberry Banana", price: 90, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Banana Bonkers" },
    { id: 1741, name: "Blueberry Banana", price: 90, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Banana Bonkers" },
    { id: 1742, name: "Butterscotch Banana", price: 90, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Banana Bonkers" },
    { id: 1743, name: "Blackcurrant Banana", price: 90, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Banana Bonkers" },
    { id: 1744, name: "Pineapple Banana", price: 90, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Banana Bonkers" },
    { id: 1745, name: "Mango Banana", price: 100, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Banana Bonkers" },
    { id: 1746, name: "Pistha Banana", price: 100, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Banana Bonkers" },
    { id: 1747, name: "Dates Banana", price: 100, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Banana Bonkers" },
    // Ice Cream Scoops - Single
    { id: 1748, name: "Vanilla Ice Cream (Single Scoop)", price: 50, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Ice Cream Scoops" },
    { id: 1749, name: "Chocolate Ice Cream (Single Scoop)", price: 60, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Ice Cream Scoops" },
    { id: 1750, name: "Strawberry Ice Cream (Single Scoop)", price: 60, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Ice Cream Scoops" },
    { id: 1751, name: "Pista Ice Cream (Single Scoop)", price: 60, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Ice Cream Scoops" },
    { id: 1752, name: "Blackcurrant Ice Cream (Single Scoop)", price: 70, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Ice Cream Scoops" },
    { id: 1753, name: "Mango Ice Cream (Single Scoop)", price: 70, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Ice Cream Scoops" },
    { id: 1754, name: "Pineapple Ice Cream (Single Scoop)", price: 70, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Ice Cream Scoops" },
    { id: 1755, name: "Butterscotch Ice Cream (Single Scoop)", price: 70, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Ice Cream Scoops" },
    { id: 1756, name: "American Nuts Ice Cream (Single Scoop)", price: 80, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Ice Cream Scoops" },
    { id: 1757, name: "Fig & Honey Ice Cream (Single Scoop)", price: 80, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Ice Cream Scoops" },
    { id: 1758, name: "Dry Fruit Ice Cream (Single Scoop)", price: 80, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Ice Cream Scoops" },
    { id: 1759, name: "PAN Ice Cream (Single Scoop)", price: 80, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Ice Cream Scoops" },
    { id: 1760, name: "Caramel Nuts Ice Cream (Single Scoop)", price: 80, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Ice Cream Scoops" },
    { id: 1761, name: "Raj Bhog Ice Cream (Single Scoop)", price: 80, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Ice Cream Scoops" },
    { id: 1762, name: "Fruit Punch Ice Cream (Single Scoop)", price: 80, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Ice Cream Scoops" },
    { id: 1763, name: "Arabian Fantasy Ice Cream (Single Scoop)", price: 80, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Ice Cream Scoops" },
    { id: 1764, name: "Kaju Kissmisse Ice Cream (Single Scoop)", price: 80, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Ice Cream Scoops" },
    // Ice Cream Scoops - Double
    { id: 1765, name: "Vanilla Ice Cream (Double Scoop)", price: 90, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Ice Cream Scoops" },
    { id: 1766, name: "Chocolate Ice Cream (Double Scoop)", price: 110, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Ice Cream Scoops" },
    { id: 1767, name: "Strawberry Ice Cream (Double Scoop)", price: 110, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Ice Cream Scoops" },
    { id: 1768, name: "Pista Ice Cream (Double Scoop)", price: 110, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Ice Cream Scoops" },
    { id: 1769, name: "Blackcurrant Ice Cream (Double Scoop)", price: 130, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Ice Cream Scoops" },
    { id: 1770, name: "Mango Ice Cream (Double Scoop)", price: 130, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Ice Cream Scoops" },
    { id: 1771, name: "Pineapple Ice Cream (Double Scoop)", price: 130, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Ice Cream Scoops" },
    { id: 1772, name: "Butterscotch Ice Cream (Double Scoop)", price: 130, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Ice Cream Scoops" },
    { id: 1773, name: "American Nuts Ice Cream (Double Scoop)", price: 150, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Ice Cream Scoops" },
    { id: 1774, name: "Fig & Honey Ice Cream (Double Scoop)", price: 150, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Ice Cream Scoops" },
    { id: 1775, name: "Dry Fruit Ice Cream (Double Scoop)", price: 150, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Ice Cream Scoops" },
    { id: 1776, name: "PAN Ice Cream (Double Scoop)", price: 150, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Ice Cream Scoops" },
    { id: 1777, name: "Caramel Nuts Ice Cream (Double Scoop)", price: 150, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Ice Cream Scoops" },
    { id: 1778, name: "Raj Bhog Ice Cream (Double Scoop)", price: 150, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Ice Cream Scoops" },
    { id: 1779, name: "Fruit Punch Ice Cream (Double Scoop)", price: 150, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Ice Cream Scoops" },
    { id: 1780, name: "Arabian Fantasy Ice Cream (Double Scoop)", price: 150, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Ice Cream Scoops" },
    { id: 1781, name: "Kaju Kissmisse Ice Cream (Double Scoop)", price: 150, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Ice Cream Scoops" },
    // Ice Cream Sundae
    { id: 1782, name: "Royal Butterscotch Ice Cream Sundae", price: 100, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Ice Cream Sundae" },
    { id: 1783, name: "Kids Special Ice Cream Sundae", price: 100, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Ice Cream Sundae" },
    { id: 1784, name: "Dark Cake Bomb Ice Cream Sundae", price: 120, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Ice Cream Sundae" },
    { id: 1785, name: "Magnum Ice Cream Sundae", price: 120, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Ice Cream Sundae" },
    { id: 1786, name: "Death By Chocolate Ice Cream Sundae", price: 150, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Ice Cream Sundae" },
    { id: 1787, name: "Gud Bud Ice Cream Sundae", price: 150, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Ice Cream Sundae" },
    { id: 1788, name: "Sizzler HOT Cake Ice Cream Sundae", price: 150, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Ice Cream Sundae" },
    { id: 1789, name: "PUTTU Ice Cream Ice Cream Sundae", price: 160, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Ice Cream Sundae" },
    // FRUIT JUICES / SHAKES
    { id: 1790, name: "Lemon Juice", price: 30, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Fruit Juices" },
    { id: 1791, name: "Lemon Soda", price: 40, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Fruit Juices" },
    { id: 1792, name: "Jaljeera Lemon", price: 40, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Fruit Juices" },
    { id: 1793, name: "Jaljeera Soda", price: 40, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Fruit Juices" },
    { id: 1794, name: "Roohafza Rocks", price: 60, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Fruit Juices" },
    { id: 1795, name: "Watermelon Juice", price: 70, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Fruit Juices" },
    { id: 1796, name: "Pineapple Juice", price: 70, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Fruit Juices" },
    { id: 1797, name: "Grapes Juice", price: 70, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Fruit Juices" },
    { id: 1798, name: "Mosambi Juice", price: 70, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Fruit Juices" },
    { id: 1799, name: "Banana Juice", price: 70, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Fruit Juices" },
    { id: 1800, name: "Carrot Juice", price: 70, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Fruit Juices" },
    { id: 1801, name: "Beetroot Juice", price: 70, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Fruit Juices" },
    { id: 1802, name: "Cucumber Juice", price: 70, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Fruit Juices" },
    { id: 1803, name: "Lime with Watermelon", price: 80, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Fruit Juices" },
    { id: 1804, name: "Apple Juice", price: 80, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Fruit Juices" },
    { id: 1805, name: "Pomegranate Juice", price: 80, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Fruit Juices" },
    { id: 1806, name: "Orange Juice", price: 80, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Fruit Juices" },
    { id: 1807, name: "Carrot Apple Juice", price: 80, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Fruit Juices" },
    { id: 1808, name: "Carrot Cucumber Juice", price: 80, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Fruit Juices" },
    { id: 1809, name: "Beetroot Carrot Juice", price: 80, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Fruit Juices" },
    { id: 1810, name: "Apple with Pomegranate Juice", price: 90, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Fruit Juices" },
    { id: 1811, name: "BCC (Beetroot + Cucumber + Carrot)", price: 90, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Fruit Juices" },
    { id: 1812, name: "ABC (Apple + Beetroot + Carrot)", price: 90, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Fruit Juices" },
    { id: 1813, name: "CAP (Carrot + Apple + Pineapple)", price: 90, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Fruit Juices" },
    { id: 1814, name: "Mixed Fruit Punch", price: 100, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Fruit Juices" },
    { id: 1815, name: "Fruit Box", price: 110, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Fruit Juices" },
    { id: 1816, name: "Healthy Box", price: 120, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Fruit Juices" },
    // FRIES
    { id: 1817, name: "French Fries", price: 80, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Fries" },
    { id: 1818, name: "Masala Fries", price: 80, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Fries" },
    { id: 1819, name: "Peri Peri Fries", price: 90, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Fries" },
    // SANDWICHES
    { id: 1820, name: "Grilled Veg Sandwich", price: 70, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Sandwiches" },
    { id: 1821, name: "Schezwan Sandwich", price: 70, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Sandwiches" },
    { id: 1822, name: "Paneer Sandwich", price: 80, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Sandwiches" },
    { id: 1823, name: "Cheese Sandwich", price: 80, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Sandwiches" },
    { id: 1824, name: "Chocolate Banana Sandwich", price: 80, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Sandwiches" },
    { id: 1825, name: "Cheese & Paneer Sandwich", price: 90, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Sandwiches" },
    { id: 1826, name: "Corn & Cheese Sandwich", price: 90, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Sandwiches" },
    // Noodles
    { id: 1827, name: "Plain Maggi", price: 40, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Noodles" },
    { id: 1828, name: "Plain Yippee", price: 40, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Noodles" },
    { id: 1829, name: "Veg Maggi", price: 50, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Noodles" },
    { id: 1830, name: "Veg Yippee", price: 50, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Noodles" },
    { id: 1831, name: "Schezwan Maggi", price: 50, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Noodles" },
    { id: 1832, name: "Schezwan Yippee", price: 50, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Noodles" },
    { id: 1833, name: "Paneer Maggi", price: 60, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Noodles" },
    { id: 1834, name: "Paneer Yippee", price: 60, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Noodles" },
    { id: 1835, name: "Cheese Maggi", price: 60, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Noodles" },
    { id: 1836, name: "Cheese Yippee", price: 60, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Noodles" },
    { id: 1837, name: "Cheese & Paneer Maggi", price: 70, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Noodles" },
    { id: 1838, name: "Cheese & Paneer Yippee", price: 70, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Noodles" },
    { id: 1839, name: "Corn & Cheese Maggi", price: 70, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Noodles" },
    { id: 1840, name: "Corn & Cheese Yippee", price: 70, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Noodles" },
    // VEG FRIES
    { id: 1841, name: "Fried Boiled Egg (2)", price: 60, restid: 14, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "Veg Fries" },
    { id: 1842, name: "Veg Party", price: 70, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Veg Fries" },
    { id: 1843, name: "Paneer Patty", price: 70, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Veg Fries" },
    { id: 1844, name: "Chilli Garlic Pops", price: 80, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Veg Fries" },
    { id: 1845, name: "Aloo Tikki", price: 80, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Veg Fries" },
    { id: 1846, name: "Veg Nuggets", price: 90, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Veg Fries" },
    { id: 1847, name: "Veg Fingers", price: 90, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Veg Fries" },
    { id: 1848, name: "Nachus", price: 90, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Veg Fries" },
    { id: 1849, name: "Cheese Shortzz", price: 90, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Veg Fries" },
    { id: 1850, name: "Momos", price: 90, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Veg Fries" },
    { id: 1851, name: "Potato Widshes", price: 100, restid: 14, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Veg Fries" },

]