export const Data = [




    //Aha kitchens

    //Non Veg Starters

    { id: 443, name: "Aaha Special Chicken Dry", price: 370, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Non Veg Starters", image: "/fooditems/1 (1).webp" },
    { id: 444, name: "Dragon Chicken", price: 370, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Non Veg Starters", image: "/fooditems/1 (2).webp" },
    { id: 445, name: "Hong-kong Chicken", price: 370, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Non Veg Starters", image: "/fooditems/1 (3).webp" },
    { id: 446, name: "Chicken Roast Boneless", price: 340, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Non Veg Starters", image: "/fooditems/1 (4).webp" },
    { id: 447, name: "Chicken Roast Bone", price: 340, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Non Veg Starters", image: "/fooditems/1 (5).webp" },
    { id: 448, name: "Chicken Pondicherry", price: 340, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Non Veg Starters", image: "/fooditems/1 (6).webp" },
    { id: 449, name: "Slice Chicken", price: 340, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Non Veg Starters", image: "/fooditems/1 (7).webp" },
    { id: 450, name: "Shejwan Chicken", price: 340, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Non Veg Starters", image: "/fooditems/1 (8).webp" },
    { id: 451, name: "Chicken Alauddin", price: 360, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Non Veg Starters", image: "/fooditems/1 (9).webp" },
    { id: 452, name: "Chicken 99", price: 340, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Non Veg Starters", image: "/fooditems/1 (10).webp" },
    { id: 453, name: "Chicken Pataka", price: 340, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Non Veg Starters", image: "/fooditems/1 (11).webp" },
    { id: 454, name: "French Onion Chicken", price: 340, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Non Veg Starters", image: "/fooditems/1 (12).webp" },
    { id: 455, name: "Chicken Majestic", price: 340, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Non Veg Starters", image: "/fooditems/1 (13).webp" },
    { id: 456, name: "Chicken Maharaja", price: 340, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Non Veg Starters", image: "/fooditems/1 (14).webp" },
    { id: 457, name: "Chicken 555", price: 340, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Non Veg Starters", image: "/fooditems/1 (15).webp" },
    { id: 458, name: "Thumsup Chicken", price: 340, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Non Veg Starters", image: "/fooditems/1 (16).webp" },
    { id: 459, name: "Chicken Basket", price: 340, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Non Veg Starters", image: "/fooditems/1 (17).webp" },
    { id: 460, name: "Lollipop", price: 360, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Non Veg Starters", image: "/fooditems/1 (18).webp" },
    { id: 461, name: "Drumstick", price: 340, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Non Veg Starters", image: "/fooditems/1 (19).webp" },
    { id: 462, name: "Kaju Chicken Dry", price: 370, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Non Veg Starters", image: "/fooditems/1 (20).webp" },
    { id: 463, name: "Shangrilla Chicken", price: 350, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Non Veg Starters", image: "/fooditems/1 (21).webp" },
    { id: 464, name: "Methi Chicken Dry", price: 340, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Non Veg Starters", image: "/fooditems/1 (22).webp" },
    { id: 465, name: "Chilli Chicken", price: 340, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Non Veg Starters", image: "/fooditems/1 (23).webp" },
    { id: 466, name: "Chicken 65", price: 340, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Non Veg Starters", image: "/fooditems/1 (24).webp" },
    { id: 467, name: "Chicken Roast", price: 340, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Non Veg Starters", image: "/fooditems/1 (25).webp" },
    { id: 468, name: "Rayalaseema Chicken Dry", price: 340, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Non Veg Starters", image: "/fooditems/1 (26).webp" },
    { id: 469, name: "Pepper Chicken", price: 340, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Non Veg Starters", image: "/fooditems/1 (27).webp" },
    { id: 470, name: "Butter Garlic Chicken", price: 360, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Non Veg Starters", image: "/fooditems/1 (28).webp" },
    { id: 471, name: "Natukodi Ghee Roast", price: 400, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Non Veg Starters", image: "/fooditems/1 (29).webp" },
    { id: 472, name: "Kamju Roast", price: 370, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Non Veg Starters", image: "/fooditems/1 (30).webp" },
    { id: 473, name: "Lemon Chicken", price: 340, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Non Veg Starters", image: "/fooditems/1 (31).webp" },
    { id: 474, name: "Chicken Appolo", price: 360, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Non Veg Starters", image: "/fooditems/1 (32).webp" },
    { id: 475, name: "Red Pepper Chicken", price: 360, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Non Veg Starters", image: "/fooditems/1 (33).webp" },
    // Veg Starters
    { id: 476, name: "AAHA SPECIAL VEG DRY", price: 290, restid: 5, button: "Add", type: "veg", symbol: "🟢", category: "Veg Starters", image: "/fooditems/1 (34).webp" },
    { id: 477, name: "VEG GULZAR", price: 220, restid: 5, button: "Add", type: "veg", symbol: "🟢", category: "Veg Starters", image: "/fooditems/1 (35).webp" },
    { id: 478, name: "VEG BASKET", price: 220, restid: 5, button: "Add", type: "veg", symbol: "🟢", category: "Veg Starters", image: "/fooditems/1 (36).webp" },
    { id: 479, name: "CRISPY VEG", price: 240, restid: 5, button: "Add", type: "veg", symbol: "🟢", category: "Veg Starters", image: "/fooditems/1 (37).webp" },
    { id: 480, name: "MUSHROOM PEPPER SALT", price: 250, restid: 5, button: "Add", type: "veg", symbol: "🟢", category: "Veg Starters", image: "/fooditems/1 (38).webp" },
    { id: 481, name: "MUSHROOM CHILLI", price: 250, restid: 5, button: "Add", type: "veg", symbol: "🟢", category: "Veg Starters", image: "/fooditems/1 (39).webp" },
    { id: 482, name: "MUSHROOM 65", price: 250, restid: 5, button: "Add", type: "veg", symbol: "🟢", category: "Veg Starters", image: "/fooditems/1 (40).webp" },
    { id: 483, name: "MUSHROOM MANCHURIYA", price: 250, restid: 5, button: "Add", type: "veg", symbol: "🟢", category: "Veg Starters", image: "/fooditems/1 (41).webp" },
    { id: 484, name: "GOLDEN FRY BABYCORN", price: 240, restid: 5, button: "Add", type: "veg", symbol: "🟢", category: "Veg Starters", image: "/fooditems/1 (42).webp" },
    { id: 485, name: "BABYCORN 65", price: 240, restid: 5, button: "Add", type: "veg", symbol: "🟢", category: "Veg Starters", image: "/fooditems/1 (43).webp" },
    { id: 486, name: "BABYCORN MAJESTIC", price: 240, restid: 5, button: "Add", type: "veg", symbol: "🟢", category: "Veg Starters", image: "/fooditems/1 (44).webp" },
    { id: 487, name: "BABYCORN MANCHURIA", price: 240, restid: 5, button: "Add", type: "veg", symbol: "🟢", category: "Veg Starters", image: "/fooditems/1 (45).webp" },
    { id: 488, name: "CRISPY CORN", price: 230, restid: 5, button: "Add", type: "veg", symbol: "🟢", category: "Veg Starters", image: "/fooditems/1 (46).webp" },
    { id: 489, name: "PANEER 65", price: 250, restid: 5, button: "Add", type: "veg", symbol: "🟢", category: "Veg Starters", image: "/fooditems/1 (47).webp" },
    { id: 490, name: "PANEER CHILLI", price: 250, restid: 5, button: "Add", type: "veg", symbol: "🟢", category: "Veg Starters", image: "/fooditems/1 (48).webp" },
    { id: 491, name: "PANEER MAJESTICK", price: 250, restid: 5, button: "Add", type: "veg", symbol: "🟢", category: "Veg Starters", image: "/fooditems/1 (49).webp" },
    { id: 492, name: "PANEER BASKET", price: 250, restid: 5, button: "Add", type: "veg", symbol: "🟢", category: "Veg Starters", image: "/fooditems/1 (50).webp" },
    { id: 493, name: "PEPPER PANEER", price: 250, restid: 5, button: "Add", type: "veg", symbol: "🟢", category: "Veg Starters", image: "/fooditems/1 (51).webp" },
    { id: 494, name: "PANEER GULZAR", price: 250, restid: 5, button: "Add", type: "veg", symbol: "🟢", category: "Veg Starters", image: "/fooditems/1 (52).webp" },
    { id: 495, name: "PANEER BHUJIA", price: 250, restid: 5, button: "Add", type: "veg", symbol: "🟢", category: "Veg Starters", image: "/fooditems/1 (53).webp" },
    { id: 496, name: "GOBI MANCHURIYA", price: 210, restid: 5, button: "Add", type: "veg", symbol: "🟢", category: "Veg Starters", image: "/fooditems/1 (54).webp" },
    { id: 497, name: "KAJU PANAEER DRY", price: 260, restid: 5, button: "Add", type: "veg", symbol: "🟢", category: "Veg Starters", image: "/fooditems/1 (55).webp" },
    { id: 498, name: "GOBI CHILLI", price: 220, restid: 5, button: "Add", type: "veg", symbol: "🟢", category: "Veg Starters", image: "/fooditems/1 (56).webp" },
    { id: 499, name: "GOBI 2025", price: 220, restid: 5, button: "Add", type: "veg", symbol: "🟢", category: "Veg Starters", image: "/fooditems/1 (57).webp" },
    { id: 500, name: "GOBI 99", price: 220, restid: 5, button: "Add", type: "veg", symbol: "🟢", category: "Veg Starters", image: "/fooditems/1 (58).webp" },
    { id: 501, name: "GOBI 65 (ROAST)", price: 210, restid: 5, button: "Add", type: "veg", symbol: "🟢", category: "Veg Starters", image: "/fooditems/1 (59).webp" },
    { id: 502, name: "KAJU ROAST", price: 300, restid: 5, button: "Add", type: "veg", symbol: "🟢", category: "Veg Starters", image: "/fooditems/1 (60).webp" },
    // Non Veg Rice items
    { id: 503, name: "Chicken Fried Rice", price: 220, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Non Veg Rice items", image: "/fooditems/1 (61).webp" },
    { id: 504, name: "Shejwan Chicken Fried Rice", price: 250, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Non Veg Rice items", image: "/fooditems/1 (62).webp" },
    { id: 505, name: "Mixed Non Veg Fried Rice", price: 270, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Non Veg Rice items", image: "/fooditems/1 (63).webp" },
    { id: 506, name: "Egg Fried Rice", price: 190, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Non Veg Rice items", image: "/fooditems/1 (64).webp" },
    { id: 507, name: "Egg Biryani", price: 220, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Non Veg Rice items", image: "/fooditems/1 (65).webp" },
    { id: 508, name: "Chicken Dum Biryani", price: 280, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Non Veg Rice items", image: "/fooditems/1 (66).webp" },
    { id: 509, name: "Chicken Roast Biryani", price: 300, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Non Veg Rice items", image: "/fooditems/1 (67).webp" },
    { id: 510, name: "Chicken Spl Biryani", price: 340, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Non Veg Rice items", image: "/fooditems/1 (68).webp" },
    { id: 511, name: "Fish Biryani", price: 340, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Non Veg Rice items", image: "/fooditems/1 (69).webp" },
    { id: 512, name: "Prawns Biryani", price: 340, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Non Veg Rice items", image: "/fooditems/1 (70).webp" },
    { id: 513, name: "Natukodi Biryani", price: 400, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Non Veg Rice items", image: "/fooditems/1 (71).webp" },
    { id: 514, name: "Chicken Family Pack (2 Biryani, 1/2 Chicken 65, 2 Roti, 1/2 Chicken Curry)", price: 900, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Non Veg Rice items", image: "/fooditems/1 (72).webp" },
    { id: 515, name: "Mutton Biryani", price: 400, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Non Veg Rice items", image: "/fooditems/1 (73).webp" },
    // Veg Rice items
    { id: 516, name: "Kaju Fried Rice", price: 250, restid: 5, button: "Add", type: "veg", symbol: "🟢", category: "Veg Rice items", image: "/fooditems/1 (74).webp" },
    { id: 517, name: "Ghee Rice", price: 250, restid: 5, button: "Add", type: "veg", symbol: "🟢", category: "Veg Rice items", image: "/fooditems/1 (75).webp" },
    { id: 518, name: "Jeera Rice", price: 180, restid: 5, button: "Add", type: "veg", symbol: "🟢", category: "Veg Rice items", image: "/fooditems/1 (76).webp" },
    { id: 519, name: "Veg Rice", price: 180, restid: 5, button: "Add", type: "veg", symbol: "🟢", category: "Veg Rice items", image: "/fooditems/1 (77).webp" },
    { id: 520, name: "Tomato Rice", price: 180, restid: 5, button: "Add", type: "veg", symbol: "🟢", category: "Veg Rice items", image: "/fooditems/1 (78).webp" },
    { id: 521, name: "Fried Rice Mushroom", price: 260, restid: 5, button: "Add", type: "veg", symbol: "🟢", category: "Veg Rice items", image: "/fooditems/1 (79).webp" },
    { id: 522, name: "Fried Rice Paneer", price: 260, restid: 5, button: "Add", type: "veg", symbol: "🟢", category: "Veg Rice items", image: "/fooditems/1 (80).webp" },
    { id: 523, name: "Gobi Fried Rice", price: 200, restid: 5, button: "Add", type: "veg", symbol: "🟢", category: "Veg Rice items", image: "/fooditems/1 (81).webp" },
    { id: 524, name: "Plain Biryani Rice", price: 200, restid: 5, button: "Add", type: "veg", symbol: "🟢", category: "Veg Rice items", image: "/fooditems/1 (82).webp" },
    { id: 525, name: "Veg Biryani", price: 230, restid: 5, button: "Add", type: "veg", symbol: "🟢", category: "Veg Rice items", image: "/fooditems/1 (83).webp" },
    { id: 526, name: "Kaju Biryani", price: 270, restid: 5, button: "Add", type: "veg", symbol: "🟢", category: "Veg Rice items", image: "/fooditems/1 (84).webp" },
    { id: 527, name: "Mushroom Biryani", price: 270, restid: 5, button: "Add", type: "veg", symbol: "🟢", category: "Veg Rice items", image: "/fooditems/1 (85).webp" },
    { id: 528, name: "Paneer Biryani", price: 270, restid: 5, button: "Add", type: "veg", symbol: "🟢", category: "Veg Rice items", image: "/fooditems/1 (86).webp" },
    { id: 529, name: "Shejwan Veg Fried Rice", price: 220, restid: 5, button: "Add", type: "veg", symbol: "🟢", category: "Veg Rice items", image: "/fooditems/1 (87).webp" },
    { id: 530, name: "Curd Rice", price: 100, restid: 5, button: "Add", type: "veg", symbol: "🟢", category: "Veg Rice items", image: "/fooditems/1 (88).webp" },
    // Roti Items
    { id: 531, name: "Roti", price: 30, restid: 5, button: "Add", type: "veg", symbol: "🟢", category: "Roti Items", image: "/fooditems/1 (89).webp" },
    { id: 532, name: "Butter Naan", price: 40, restid: 5, button: "Add", type: "veg", symbol: "🟢", category: "Roti Items", image: "/fooditems/1 (90).webp" },
    { id: 533, name: "Butter Roti", price: 35, restid: 5, button: "Add", type: "veg", symbol: "🟢", category: "Roti Items", image: "/fooditems/1 (91).webp" },
    { id: 534, name: "Butter Kulcha", price: 50, restid: 5, button: "Add", type: "veg", symbol: "🟢", category: "Roti Items", image: "/fooditems/1 (92).webp" },
    { id: 535, name: "Masala Kulcha", price: 60, restid: 5, button: "Add", type: "veg", symbol: "🟢", category: "Roti Items", image: "/fooditems/1 (93).webp" },
    { id: 536, name: "Garlic Naan", price: 70, restid: 5, button: "Add", type: "veg", symbol: "🟢", category: "Roti Items", image: "/fooditems/1 (94).webp" },
    { id: 537, name: "Pudina Roti", price: 40, restid: 5, button: "Add", type: "veg", symbol: "🟢", category: "Roti Items", image: "/fooditems/1 (95).webp" },
    { id: 538, name: "Methi Roti", price: 40, restid: 5, button: "Add", type: "veg", symbol: "🟢", category: "Roti Items", image: "/fooditems/1 (96).webp" },
    { id: 539, name: "Parota", price: 30, restid: 5, button: "Add", type: "veg", symbol: "🟢", category: "Roti Items", image: "/fooditems/1 (97).webp" },
    // Nonveg Gravy
    { id: 540, name: "Aaha Special Chicken Curry", price: 320, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Nonveg Gravy", image: "/fooditems/1 (98).webp" },
    { id: 541, name: "Butter Chicken", price: 330, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Nonveg Gravy", image: "/fooditems/1 (99).webp" },
    { id: 542, name: "Chicken Moughlai", price: 330, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Nonveg Gravy", image: "/fooditems/1 (100).webp" },
    { id: 543, name: "Methi Chicken", price: 330, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Nonveg Gravy", image: "/fooditems/1 (101).webp" },
    { id: 544, name: "Kadai Chicken", price: 330, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Nonveg Gravy", image: "/fooditems/1 (102).webp" },
    { id: 545, name: "Andhra Chicken", price: 330, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Nonveg Gravy", image: "/fooditems/1 (103).webp" },
    { id: 546, name: "Rayalaseema Chicken", price: 330, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Nonveg Gravy", image: "/fooditems/1 (104).webp" },
    { id: 547, name: "Gongura Chicken", price: 330, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Nonveg Gravy", image: "/fooditems/1 (105).webp" },
    { id: 548, name: "Chicken Mandakini", price: 360, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Nonveg Gravy", image: "/fooditems/1 (106).webp" },
    { id: 549, name: "Chicken Afghani", price: 340, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Nonveg Gravy", image: "/fooditems/1 (107).webp" },
    { id: 550, name: "Chicken Rampuri", price: 340, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Nonveg Gravy", image: "/fooditems/1 (108).webp" },
    { id: 551, name: "Chicken Kolhapuri", price: 340, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Nonveg Gravy", image: "/fooditems/1 (109).webp" },
    { id: 552, name: "Capsicum Chicken", price: 330, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Nonveg Gravy", image: "/fooditems/1 (110).webp" },
    { id: 553, name: "Ginger Chicken", price: 330, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Nonveg Gravy", image: "/fooditems/1 (111).webp" },
    { id: 554, name: "Chicken Keema Curry", price: 340, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Nonveg Gravy", image: "/fooditems/1 (112).webp" },
    { id: 555, name: "Chicken Punjabi", price: 360, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Nonveg Gravy", image: "/fooditems/1 (113).webp" },
    { id: 556, name: "Chicken Basanti", price: 360, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Nonveg Gravy", image: "/fooditems/1 (114).webp" },
    { id: 557, name: "Chicken Tikka Masala", price: 360, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Nonveg Gravy", image: "/fooditems/1 (115).webp" },
    { id: 558, name: "Andhra Chicken Curry (Bone)", price: 330, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Nonveg Gravy", image: "/fooditems/1 (116).webp" },
    { id: 559, name: "Chicken Curry (Bone)", price: 330, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Nonveg Gravy", image: "/fooditems/1 (117).webp" },
    // Veg Curry
    { id: 560, name: "AAHA SPECIAL VEG CURRY", price: 280, restid: 5, button: "Add", type: "veg", symbol: "🟢", category: "Veg Curry", image: "/fooditems/1 (118).webp" },
    { id: 561, name: "MALAI KOFTA", price: 270, restid: 5, button: "Add", type: "veg", symbol: "🟢", category: "Veg Curry", image: "/fooditems/1 (119).webp" },
    { id: 562, name: "PALAK KOFTA", price: 270, restid: 5, button: "Add", type: "veg", symbol: "🟢", category: "Veg Curry", image: "/fooditems/1 (120).webp" },
    { id: 563, name: "VEG MAHARANI", price: 230, restid: 5, button: "Add", type: "veg", symbol: "🟢", category: "Veg Curry", image: "/fooditems/1 (121).webp" },
    { id: 564, name: "PANEER BUTTER MASALA", price: 240, restid: 5, button: "Add", type: "veg", symbol: "🟢", category: "Veg Curry", image: "/fooditems/1 (122).webp" },
    { id: 565, name: "PALAK PANEER", price: 230, restid: 5, button: "Add", type: "veg", symbol: "🟢", category: "Veg Curry", image: "/fooditems/1 (123).webp" },
    { id: 566, name: "PANEER SHAHI KURMA", price: 240, restid: 5, button: "Add", type: "veg", symbol: "🟢", category: "Veg Curry", image: "/fooditems/1 (124).webp" },
    { id: 567, name: "PANEER TIKKA MASALA", price: 270, restid: 5, button: "Add", type: "veg", symbol: "🟢", category: "Veg Curry", image: "/fooditems/1 (125).webp" },
    { id: 568, name: "MIXED VEG CURRY", price: 210, restid: 5, button: "Add", type: "veg", symbol: "🟢", category: "Veg Curry", image: "/fooditems/1 (126).webp" },
    { id: 569, name: "VEG KADAI", price: 230, restid: 5, button: "Add", type: "veg", symbol: "🟢", category: "Veg Curry", image: "/fooditems/1 (127).webp" },
    { id: 570, name: "PANEER KADAI", price: 230, restid: 5, button: "Add", type: "veg", symbol: "🟢", category: "Veg Curry", image: "/fooditems/1 (128).webp" },
    { id: 571, name: "MUSHROOM KADAI", price: 230, restid: 5, button: "Add", type: "veg", symbol: "🟢", category: "Veg Curry", image: "/fooditems/1 (129).webp" },
    { id: 572, name: "MUSHROOM CURRY", price: 230, restid: 5, button: "Add", type: "veg", symbol: "🟢", category: "Veg Curry", image: "/fooditems/1 (130).webp" },
    { id: 573, name: "KAJU CURRY", price: 270, restid: 5, button: "Add", type: "veg", symbol: "🟢", category: "Veg Curry", image: "/fooditems/1 (131).webp" },
    { id: 574, name: "PANEER KAJU CURRY", price: 290, restid: 5, button: "Add", type: "veg", symbol: "🟢", category: "Veg Curry", image: "/fooditems/1 (132).webp" },
    { id: 575, name: "TOMATO CURRY", price: 190, restid: 5, button: "Add", type: "veg", symbol: "🟢", category: "Veg Curry", image: "/fooditems/1 (133).webp" },
    { id: 576, name: "GOBI MASALA", price: 200, restid: 5, button: "Add", type: "veg", symbol: "🟢", category: "Veg Curry", image: "/fooditems/1 (134).webp" },
    { id: 577, name: "METHI PANEER", price: 230, restid: 5, button: "Add", type: "veg", symbol: "🟢", category: "Veg Curry", image: "/fooditems/1 (135).webp" },
    { id: 578, name: "METHI CHAMAN", price: 240, restid: 5, button: "Add", type: "veg", symbol: "🟢", category: "Veg Curry", image: "/fooditems/1 (136).webp" },
    { id: 579, name: "VEG RAYALASEEMA", price: 210, restid: 5, button: "Add", type: "veg", symbol: "🟢", category: "Veg Curry", image: "/fooditems/1 (137).webp" },
    { id: 580, name: "VEG HYDERABADI", price: 210, restid: 5, button: "Add", type: "veg", symbol: "🟢", category: "Veg Curry", image: "/fooditems/1 (138).webp" },
    { id: 581, name: "DAL FRY", price: 160, restid: 5, button: "Add", type: "veg", symbol: "🟢", category: "Veg Curry", image: "/fooditems/1 (139).webp" },
    { id: 582, name: "DAL TADKA", price: 160, restid: 5, button: "Add", type: "veg", symbol: "🟢", category: "Veg Curry", image: "/fooditems/1 (140).webp" },
    { id: 583, name: "DAL MAKHANI", price: 200, restid: 5, button: "Add", type: "veg", symbol: "🟢", category: "Veg Curry", image: "/fooditems/1 (141).webp" },
    { id: 584, name: "KAJU TOMATO", price: 260, restid: 5, button: "Add", type: "veg", symbol: "🟢", category: "Veg Curry", image: "/fooditems/1 (142).webp" },
    { id: 585, name: "VEG KOLLAPURI", price: 220, restid: 5, button: "Add", type: "veg", symbol: "🟢", category: "Veg Curry", image: "/fooditems/1 (143).webp" },
    { id: 586, name: "VEG CHAT PATA", price: 240, restid: 5, button: "Add", type: "veg", symbol: "🟢", category: "Veg Curry", image: "/fooditems/1 (144).webp" },
    // Mast Mutton
    { id: 587, name: "Mutton Ghee Roast", price: 420, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Mast Mutton", image: "/fooditems/1 (145).webp" },
    { id: 588, name: "Mutton Roast", price: 420, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Mast Mutton", image: "/fooditems/1 (146).webp" },
    { id: 589, name: "Mutton Curry", price: 420, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Mast Mutton", image: "/fooditems/1 (147).webp" },
    { id: 590, name: "Mutton Kadai", price: 420, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Mast Mutton", image: "/fooditems/1 (148).webp" },
    { id: 591, name: "Butter Mutton", price: 420, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Mast Mutton", image: "/fooditems/1 (149).webp" },
    { id: 592, name: "Mutton Moghulai", price: 420, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Mast Mutton", image: "/fooditems/1 (150).webp" },
    // Seafood
    { id: 593, name: "Fish Fry", price: 350, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Seafood", image: "/fooditems/1 (151).webp" },
    { id: 594, name: "Fish 65", price: 350, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Seafood", image: "/fooditems/1 (152).webp" },
    { id: 595, name: "Apollo Fish", price: 350, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Seafood", image: "/fooditems/1 (153).webp" },
    { id: 596, name: "Fish Manchuria", price: 350, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Seafood", image: "/fooditems/1 (154).webp" },
    { id: 597, name: "Fish 555", price: 350, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Seafood", image: "/fooditems/1 (155).webp" },
    { id: 598, name: "Red Pepper Fish", price: 350, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Seafood", image: "/fooditems/1 (156).webp" },
    { id: 599, name: "Lemon Fish", price: 350, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Seafood", image: "/fooditems/1 (157).webp" },
    { id: 600, name: "Fish Gravy", price: 350, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Seafood", image: "/fooditems/1 (158).webp" },
    { id: 601, name: "Fish Masala", price: 350, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Seafood", image: "/fooditems/1 (159).webp" },
    { id: 602, name: "Aaha Special Fish Curry", price: 360, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Seafood", image: "/fooditems/1 (160).webp" },
    { id: 603, name: "Loose Prawns", price: 350, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Seafood", image: "/fooditems/1 (161).webp" },
    { id: 604, name: "Pepper Prawns", price: 350, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Seafood", image: "/fooditems/1 (162).webp" },
    { id: 605, name: "Butter Garlic Prawns", price: 370, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Seafood", image: "/fooditems/1 (163).webp" },
    { id: 606, name: "Shejwan Prawns", price: 370, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Seafood", image: "/fooditems/1 (164).webp" },
    { id: 607, name: "Golden Prawns", price: 350, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Seafood", image: "/fooditems/1 (165).webp" },
    { id: 608, name: "Prawns Chilli", price: 350, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Seafood", image: "/fooditems/1 (166).webp" },
    { id: 609, name: "Lemon Prawns", price: 350, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Seafood", image: "/fooditems/1 (167).webp" },
    { id: 610, name: "Prawns Curry", price: 350, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Seafood", image: "/fooditems/1 (168).webp" },
    { id: 611, name: "Aaha Special Prawns Curry", price: 360, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Seafood", image: "/fooditems/1 (169).webp" },
    // Egg Items
    { id: 612, name: "Egg Basket", price: 200, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Egg Items", image: "/fooditems/1 (170).webp" },
    { id: 613, name: "Egg Roast", price: 200, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Egg Items", image: "/fooditems/1 (171).webp" },
    { id: 614, name: "Egg Gulzar", price: 200, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Egg Items", image: "/fooditems/1 (172).webp" },
    { id: 615, name: "Egg Chilli", price: 200, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Egg Items", image: "/fooditems/1 (173).webp" },
    { id: 616, name: "Egg Allauddin", price: 200, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Egg Items", image: "/fooditems/1 (174).webp" },
    { id: 617, name: "Egg Masala", price: 190, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Egg Items", image: "/fooditems/1 (175).webp" },
    { id: 618, name: "Egg Tomato", price: 190, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Egg Items", image: "/fooditems/1 (176).webp" },
    { id: 619, name: "Egg Burj", price: 140, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Egg Items", image: "/fooditems/1 (177).webp" },
    // Tandoori
    { id: 620, name: "Full Murgi", price: 550, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Tandoori", image: "/fooditems/1 (178).webp" },
    { id: 621, name: "Half Murgi", price: 300, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Tandoori", image: "/fooditems/1 (179).webp" },
    { id: 622, name: "Tangdi Kebab", price: 300, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Tandoori", image: "/fooditems/1 (180).webp" },
    { id: 623, name: "Chicken Tikka", price: 320, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Tandoori", image: "/fooditems/1 (181).webp" },
    { id: 624, name: "Paneer Tikka", price: 320, restid: 5, button: "Add", type: "veg", symbol: "🟢", category: "Tandoori", image: "/fooditems/1 (182).webp" },
    { id: 625, name: "Palak Kabab", price: 320, restid: 5, button: "Add", type: "veg", symbol: "🟢", category: "Tandoori", image: "/fooditems/1 (183).webp" },
    { id: 626, name: "Malai Kabab", price: 320, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Tandoori", image: "/fooditems/1 (184).webp" },
    { id: 627, name: "Hara Bara Kabab", price: 320, restid: 5, button: "Add", type: "veg", symbol: "🟢", category: "Tandoori", image: "/fooditems/1 (185).webp" },
    // Aaha Special
    { id: 628, name: "Mutton Talakaya", price: 400, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Aaha Special", image: "/fooditems/1 (186).webp" },
    { id: 629, name: "Natukodi Pulusu", price: 400, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Aaha Special", image: "/fooditems/1 (187).webp" },
    { id: 630, name: "Raagi Mudda", price: 120, restid: 5, button: "Add", type: "veg", symbol: "🟢", category: "Aaha Special", image: "/fooditems/1 (188).webp" },
    //pot biryani
    { id: 631, name: "Mutton Pot Biryani", price: 700, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "pot biryani", image: "/fooditems/1 (189).webp" },
    { id: 632, name: "Chicken Pot Biryani", price: 500, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "pot biryani", image: "/fooditems/1 (190).webp" },
    // Noodles
    { id: 633, name: "Veg Soft Noodles", price: 170, restid: 5, button: "Add", type: "veg", symbol: "🟢", category: "Noodles", image: "/fooditems/1 (191).webp" },
    { id: 634, name: "Egg Noodles", price: 190, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Noodles", image: "/fooditems/1 (192).webp" },
    { id: 635, name: "Chicken Noodles", price: 220, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", category: "Noodles", image: "/fooditems/1 (193).webp" }


];