export const Data = [
   //salads
   { id: 1, name: "Tandoori Tikka Salad (Veg)", price: 150, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (42).webp" },
   { id: 2, name: "Tandoori Tikka Salad (Non-Veg)", price: 175, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (43).webp" },
   { id: 3, name: "Russian Salad", price: 150, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (44).webp" },
   { id: 4, name: "Fruit Chat", price: 150, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (45).webp" },
   { id: 5, name: "Aloo Papdi Chat", price: 150, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (46).webp" },
   { id: 6, name: "Green Salad", price: 125, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (47).webp" },
   { id: 7, name: "Tossed Salad", price: 125, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (48).webp" },


   //continental
   { id: 8, name: "Fish Fingers", price: 275, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (49).webp" },
   { id: 9, name: "Fish n Chips", price: 295, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (50).webp" },
   { id: 10, name: "Chicken Chips", price: 255, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (51).webp" },
   //continantal pasta
   { id: 11, name: "Napolitana Pasta (Penne)", price: 275, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (52).webp" },
   { id: 12, name: "Napolitana Pasta (Macaroni)", price: 275, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (53).webp" },
   { id: 13, name: "Napolitana Pasta (Spaghetti)", price: 275, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (54).webp" },
   { id: 14, name: "Napolitana Pasta (Fusilli)", price: 275, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (55).webp" },
   { id: 15, name: "Arrabiata Pasta (Penne)", price: 275, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (56).webp" },
   { id: 16, name: "Arrabiata Pasta (Macaroni)", price: 275, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (57).webp" },
   { id: 17, name: "Arrabiata Pasta (Spaghetti)", price: 275, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (58).webp" },
   { id: 18, name: "Arrabiata Pasta (Fusilli)", price: 275, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (59).webp" },
   { id: 19, name: "Pesto Pasta (Penne)", price: 275, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (60).webp" },
   { id: 20, name: "Pesto Pasta (Macaroni)", price: 275, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (61).webp" },

   { id: 21, name: "Pesto Pasta (Spaghetti)", price: 275, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (62).webp" },
   { id: 22, name: "Pesto Pasta (Fusilli)", price: 275, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (63).webp" },


   //chainees
   { id: 23, name: "Crispy Baby Corn", price: 275, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (64).webp" },
   { id: 24, name: "Schezwan Baby Corn", price: 275, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (65).webp" },
   { id: 25, name: "Baby Corn Manchurian", price: 275, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (66).webp" },
   { id: 26, name: "Vegetables Manchuria", price: 250, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (67).webp" },
   { id: 27, name: "Gobi Manchuria", price: 250, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (68).webp" },
   { id: 28, name: "Gobi 65", price: 250, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (69).webp" },
   { id: 29, name: "Paneer Chilli", price: 315, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (70).webp" },
   { id: 30, name: "Paneer Schezwan", price: 315, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (71).webp" },
   { id: 31, name: "Salt Pepper Paneer", price: 315, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (72).webp" },
   { id: 32, name: "Paneer 65", price: 315, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (73).webp" },
   { id: 33, name: "Paneer Majestic", price: 315, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (74).webp" },
   { id: 34, name: "Mushroom Chilli", price: 275, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (75).webp" },
   { id: 35, name: "Salt Pepper Mushroom", price: 275, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (76).webp" },
   { id: 36, name: "Kung Pao Mushroom", price: 275, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (77).webp" },
   { id: 37, name: "Crispy Corn Kernel", price: 250, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (78).webp" },
   { id: 38, name: "Spring Rolls with Hot Chilli Dip", price: 250, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (79).webp" },
   { id: 39, name: "Veg Platter", price: 660, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (80).webp" },
   { id: 40, name: "Egg 65", price: 255, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (81).webp" },
   { id: 41, name: "Egg Chilli", price: 255, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (82).webp" },
   { id: 42, name: "Egg Manchuria", price: 255, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (83).webp" },
   { id: 43, name: "Egg Schezwan", price: 255, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (84).webp" },
   { id: 44, name: "Chicken 65", price: 325, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (85).webp" },
   { id: 45, name: "Chicken Chilli", price: 325, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (86).webp" },
   { id: 46, name: "Chicken Manchuria", price: 325, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (87).webp" },
   { id: 47, name: "Salt Pepper Chicken", price: 325, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (88).webp" },
   { id: 48, name: "Dragon Chicken", price: 340, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (89).webp" },
   { id: 49, name: "Butter Garlic Chicken", price: 340, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (90).webp" },
   { id: 50, name: "Chicken Drums of Heaven (Dry)", price: 360, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (91).webp" },
   { id: 51, name: "Chicken Lollipop (Wet)", price: 360, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (92).webp" },
   { id: 52, name: "Fish 65", price: 355, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (93).webp" },
   { id: 53, name: "Fish Chilli", price: 355, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (94).webp" },
   { id: 54, name: "Fish Manchuria", price: 355, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (95).webp" },
   { id: 55, name: "Prawns Salt & Pepper", price: 395, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (96).webp" },
   { id: 56, name: "Prawns Chilli", price: 395, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (97).webp" },
   { id: 57, name: "Loose Prawns", price: 395, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (98).webp" },
   { id: 58, name: "Butter Garlic Prawns", price: 395, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (99).webp" },
   { id: 59, name: "Apollo Fish", price: 355, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (100).webp" },
   { id: 60, name: "Non-Veg Platter", price: 780, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (101).webp" },

   //tandoori
   { id: 61, name: "Veg Seekh Kebab", price: 275, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (102).webp" },
   { id: 62, name: "Tandoori Gobi", price: 275, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (103).webp" },
   { id: 63, name: "Stuffed Mushroom", price: 330, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (104).webp" },
   { id: 64, name: "Paneer Achari Tikka", price: 350, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (105).webp" },
   { id: 65, name: "Paneer Malai Tikka", price: 350, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (106).webp" },
   { id: 66, name: "Veg Platter", price: 550, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (107).webp" },
   { id: 67, name: "Chicken Tikka", price: 350, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (108).webp" },
   { id: 68, name: "Tangdi Kebab", price: 375, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (109).webp" },
   { id: 69, name: "Kalmi Kebab", price: 375, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (110).webp" },
   { id: 70, name: "Haryali Fish Tikka", price: 375, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (111).webp" },
   { id: 71, name: "Ajwain Fish Tikka", price: 375, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (112).webp" },
   { id: 72, name: "Tandoori Chicken (Half)", price: 350, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (113).webp" },
   { id: 73, name: "Tandoori Chicken (Full)", price: 650, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (114).webp" },
   { id: 74, name: "Chicken Seekh Kebab", price: 390, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (115).webp" },
   { id: 75, name: "Mutton Seekh Kebab", price: 425, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (116).webp" },
   { id: 76, name: "Mutton Shami Kebab", price: 425, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (117).webp" },
   { id: 77, name: "Non-Veg Platter", price: 799, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (118).webp" },



   //biryanies and pulaous
   { id: 78, name: "Veg Dum Biryani", price: 255, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (119).webp" },
   { id: 79, name: "Paneer Biryani", price: 275, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (120).webp" },
   { id: 80, name: "Mushroom Biryani", price: 275, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (121).webp" },
   { id: 81, name: "Special Veg Biryani", price: 285, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (122).webp" },
   { id: 82, name: "Ulavacharu Biryani", price: 275, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (123).webp" },
   { id: 83, name: "Veg Pulao", price: 225, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (124).webp" },
   { id: 84, name: "Kaju Corn Pulao", price: 300, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (125).webp" },
   { id: 85, name: "Egg Biryani", price: 250, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (126).webp" },
   { id: 86, name: "Devil Egg Biryani", price: 270, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (127).webp" },
   { id: 87, name: "Chicken Dum Biryani", price: 315, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (128).webp" },
   { id: 88, name: "Chicken Fry Piece Biryani", price: 335, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (129).webp" },
   { id: 89, name: "Special Chicken Biryani", price: 355, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (130).webp" },
   { id: 90, name: "Chicken 65 Biryani", price: 355, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (131).webp" },
   { id: 91, name: "Chicken Tikka Biryani", price: 355, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (132).webp" },
   { id: 92, name: "Mutton Biryani", price: 415, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (133).webp" },
   { id: 93, name: "Mutton Kheema Biryani", price: 455, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (134).webp" },
   { id: 94, name: "Gongura Mutton Biryani", price: 420, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (135).webp" },
   { id: 95, name: "VIVA Spl. Milao Biryani", price: 425, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (136).webp" },
   { id: 96, name: "Konaseema Kodi Pulao", price: 335, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (137).webp" },
   { id: 97, name: "Ulavacharu Kodi Pulao", price: 335, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (138).webp" },
   { id: 98, name: "Prawns Biryani", price: 390, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (139).webp" },
   { id: 99, name: "Fish Biryani", price: 390, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (140).webp" },

   //rice items
   { id: 100, name: "Steamed Rice", price: 110, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (141).webp" },
   { id: 101, name: "Sambar Rice", price: 175, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (142).webp" },
   { id: 102, name: "Chicken Sambar Rice", price: 195, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (143).webp" },
   { id: 103, name: "Muddha Pappu Avakai Annam", price: 175, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (144).webp" },
   { id: 104, name: "Raagi Sangati", price: 120, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (145).webp" },
   { id: 105, name: "Curd Rice", price: 155, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (146).webp" },
   { id: 106, name: "Special Curd Rice", price: 175, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (147).webp" },
   { id: 107, name: "Plain Curd", price: 60, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (148).webp" },


   //breads
   { id: 108, name: "Plain Roti", price: 45, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (149).webp" },
   { id: 109, name: "Butter Roti", price: 55, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (150).webp" },
   { id: 110, name: "Plain Pulka", price: 45, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (151).webp" },
   { id: 111, name: "Butter Pulka", price: 55, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (152).webp" },
   { id: 112, name: "Plain Kulcha", price: 75, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (153).webp" },
   { id: 113, name: "Stuffed Kulcha", price: 85, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (154).webp" },
   { id: 114, name: "Plain Naan", price: 55, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (155).webp" },
   { id: 115, name: "Butter Naan", price: 65, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (156).webp" },
   { id: 116, name: "Garlic Naan", price: 65, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (157).webp" },
   { id: 117, name: "Laccha Paratha", price: 65, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (158).webp" },
   { id: 118, name: "Aloo Paratha", price: 75, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (159).webp" },
   { id: 119, name: "Paneer Paratha", price: 105, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (160).webp" },

   //rice items
   { id: 120, name: "Veg Fried Rice", price: 240, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (161).webp" },
   { id: 121, name: "Non-Veg Fried Rice", price: 275, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (162).webp" },
   { id: 122, name: "Schezwan Veg Fried Rice", price: 240, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (163).webp" },
   { id: 123, name: "Schezwan Non-Veg Fried Rice", price: 275, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (164).webp" },
   { id: 124, name: "Hakka Veg Fried Rice", price: 240, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (165).webp" },
   { id: 125, name: "Hakka Non-Veg Fried Rice", price: 275, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (166).webp" },
   { id: 126, name: "Chilli Garlic Veg Fried Rice", price: 240, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (167).webp" },
   { id: 127, name: "Chilli Garlic Non-Veg Fried Rice", price: 275, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (168).webp" },

   //noodils
   { id: 128, name: "Veg Wok Tossed Noodles", price: 250, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (169).webp" },
   { id: 129, name: "Non-Veg Wok Tossed Noodles", price: 275, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (170).webp" },
   { id: 130, name: "Soft Veg Noodles", price: 250, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (171).webp" },
   { id: 131, name: "Soft Non-Veg Noodles", price: 275, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (172).webp" },
   { id: 132, name: "Schezwan Veg Noodles", price: 250, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (173).webp" },
   { id: 133, name: "Schezwan Non-Veg Noodles", price: 275, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (174).webp" },


   //Chopsey
   { id: 134, name: "American Veg Chopsey", price: 250, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (175).webp" },
   { id: 135, name: "American Non-Veg Chopsey", price: 275, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (176).webp" },
   { id: 136, name: "Chinese Veg Chopsey", price: 250, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (177).webp" },
   { id: 137, name: "Chinese Non-Veg Chopsey", price: 275, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (178).webp" },


   //Sandwitch
   { id: 138, name: "Veg Sandwich", price: 175, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (179).webp" },
   { id: 139, name: "Cheese Pineapple Sandwich", price: 190, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (180).webp" },
   { id: 140, name: "Veg Club Sandwich", price: 175, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (181).webp" },
   { id: 141, name: "Chicken Club Sandwich", price: 225, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (182).webp" },
   { id: 142, name: "Veg Tikka Sandwich", price: 190, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (183).webp" },
   { id: 143, name: "Chicken Tikka Sandwich", price: 225, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (184).webp" },


   //burger
   { id: 144, name: "Veg Burger", price: 175, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (185).webp" },
   { id: 145, name: "Chicken Burger", price: 225, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (186).webp" },


   //pizza
   { id: 146, name: "Veg Pizza", price: 175, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (187).webp" },
   { id: 147, name: "Chicken Pizza", price: 225, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (188).webp" },
   { id: 148, name: "Veg Tikka Pizza", price: 175, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (189).webp" },
   { id: 149, name: "Chicken Tikka Pizza", price: 225, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (190).webp" },

   //deserts
   { id: 150, name: "Gulab Jamun", price: 145, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (191).webp" },
   { id: 151, name: "Gulab Jamun with Ice Cream", price: 185, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (192).webp" },
   { id: 152, name: "Fruit Salad with Ice Cream", price: 185, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (193).webp" },
   { id: 153, name: "Gajar Ka Halwa", price: 155, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (194).webp" },
   { id: 154, name: "Caramel Custard", price: 155, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (195).webp" },
   { id: 155, name: "Banana Split", price: 195, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (196).webp" },
   { id: 156, name: "Vanilla Ice Cream", price: 90, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (197).webp" },
   { id: 157, name: "Strawberry Ice Cream", price: 90, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (198).webp" },
   { id: 158, name: "Mango Ice Cream", price: 90, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (199).webp" },
   { id: 159, name: "Chocolate Ice Cream", price: 90, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (200).webp" },
   { id: 160, name: "Brownie with Chocolate Fudge", price: 250, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (201).webp" },

   //main corece
   { id: 161, name: "Dal Fry", price: 225, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (202).webp" },
   { id: 162, name: "Dal Tadka", price: 225, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (203).webp" },
   { id: 163, name: "Alu Jeera", price: 255, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (204).webp" },
   { id: 164, name: "Alu Gobi", price: 255, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (205).webp" },
   { id: 165, name: "Kadai Veg", price: 275, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (206).webp" },
   { id: 166, name: "Veg Kolhapuri", price: 275, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (207).webp" },
   { id: 167, name: "Mushroom Mutter Masala", price: 275, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (208).webp" },
   { id: 168, name: "Mushroom Curry", price: 275, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (209).webp" },
   { id: 169, name: "Paneer Butter Masala", price: 305, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (210).webp" },
   { id: 170, name: "Paneer Mutter Masala", price: 305, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (211).webp" },
   { id: 171, name: "Kadai Paneer", price: 305, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (212).webp" },
   { id: 172, name: "Palak Paneer", price: 305, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (213).webp" },
   { id: 173, name: "Paneer Tikka Masala", price: 315, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (214).webp" },
   { id: 174, name: "Malai Kofta", price: 315, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (215).webp" },
   { id: 175, name: "Kaju Tomato Curry", price: 295, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (216).webp" },
   { id: 176, name: "Kaju Paneer Curry", price: 325, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (217).webp" },
   { id: 177, name: "Egg Bhurji", price: 265, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (218).webp" },
   { id: 178, name: "Egg Kheema Curry", price: 265, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (219).webp" },
   { id: 179, name: "Butter Chicken", price: 325, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (220).webp" },
   { id: 180, name: "Mutton Rogan Josh", price: 425, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (221).webp" },
   { id: 181, name: "Mutton Kheema Masala", price: 475, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (222).webp" },
   { id: 182, name: "Royallu Pulusu", price: 395, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (223).webp" },
   { id: 183, name: "Kodi Pulusu", price: 325, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (224).webp" },
   { id: 184, name: "Mutton Pulusu", price: 425, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (225).webp" },
   { id: 185, name: "Royallu Chettinadu", price: 395, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (226).webp" },
   { id: 186, name: "Kodi Chettinadu", price: 325, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (227).webp" },
   { id: 187, name: "Mutton Chettinadu", price: 426, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (228).webp" },
   { id: 188, name: "Pardha Chicken Curry", price: 335, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (229).webp" },
   { id: 189, name: "Chicken Tikka Masala", price: 335, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (230).webp" },
   { id: 190, name: "Murgh Darbari", price: 399, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (231).webp" },
   { id: 191, name: "Hyderabad Fish Curry", price: 325, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (232).webp" },

   //VIVA specials
   { id: 192, name: "Konaseema Panneer Vepudu", price: 350, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (233).webp" },
   { id: 193, name: "Kothimeera Puttagodugu", price: 275, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (234).webp" },
   { id: 194, name: "Malai Broccolli", price: 315, restid: 2, button: "Add", type: "veg", symbol: "🟩", image: "/fooditems/1 (235).webp" },
   { id: 195, name: "Bhimavaram Kodi Vepudu", price: 350, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (236).webp" },
   { id: 196, name: "Pacchi Mirchi Kodi Kebab", price: 350, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (237).webp" },
   { id: 197, name: "Peri Peri Chicken Tikka", price: 360, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (238).webp" },
   { id: 198, name: "Ellipaya Kodi Vepudu", price: 335, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (239).webp" },
   { id: 199, name: "Mutton Ghee Roast", price: 425, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (240).webp" },
   { id: 200, name: "Royyala Iguru", price: 390, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (241).webp" },
   { id: 201, name: "Andhra Chepa Vepudu", price: 350, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (242).webp" },
   { id: 202, name: "Miriyalu Royyalu", price: 450, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (243).webp" },
   { id: 203, name: "Miriyalu Kodi", price: 350, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (244).webp" },
   { id: 204, name: "Miriyalu Mamsam", price: 425, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (245).webp" },
   { id: 205, name: "Mirapakaya Royyalu", price: 450, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (246).webp" },
   { id: 206, name: "Mirapakaya Kodi", price: 350, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (247).webp" },
   { id: 207, name: "Mirapakaya Mamsam", price: 425, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (248).webp" }


];