export const Data = [


    //// HOTEL HINDUSTAN////
    // veg starters
    { id: 1453, name: "Veg Basket", price: 180, restid: 13, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "veg starters" },
    { id: 1454, name: "Veg Shangrilla", price: 190, restid: 13, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "veg starters" },
    { id: 1455, name: "Veg Crispy", price: 180, restid: 13, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "veg starters" },
    { id: 1456, name: "Alu - 65", price: 180, restid: 13, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "veg starters" },
    { id: 1457, name: "Alu Manchuria", price: 180, restid: 13, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "veg starters" },
    { id: 1458, name: "Gobi - 65", price: 170, restid: 13, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "veg starters" },
    { id: 1459, name: "Gobi Chilly", price: 180, restid: 13, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "veg starters" },
    { id: 1460, name: "Gobi Manchuria", price: 180, restid: 13, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "veg starters" },
    { id: 1461, name: "Baby Corn 65", price: 190, restid: 13, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "veg starters" },
    { id: 1462, name: "Baby Corn Chilly", price: 190, restid: 13, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "veg starters" },
    { id: 1463, name: "Baby Corn Manchuria", price: 190, restid: 13, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "veg starters" },
    { id: 1464, name: "Mashroom - 65", price: 200, restid: 13, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "veg starters" },
    { id: 1465, name: "Mashroom Chilly", price: 210, restid: 13, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "veg starters" },
    { id: 1466, name: "Mashroom Manchuria", price: 210, restid: 13, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "veg starters" },
    { id: 1467, name: "Panner - 65", price: 220, restid: 13, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "veg starters" },
    { id: 1468, name: "Panner Manchuria", price: 230, restid: 13, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "veg starters" },
    { id: 1469, name: "Panner Majestic", price: 260, restid: 13, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "veg starters" },
    { id: 1470, name: "Panner Chilly", price: 230, restid: 13, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "veg starters" },
    // veg gravy 
    { id: 1471, name: "Panner Kollapuri", price: 220, restid: 13, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "veg gravy" },
    { id: 1472, name: "Panner Butter Masala", price: 220, restid: 13, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "veg gravy" },
    { id: 1473, name: "Panner Sahi Kurma", price: 220, restid: 13, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "veg gravy" },
    { id: 1474, name: "Stuffed Panner", price: 240, restid: 13, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "veg gravy" },
    { id: 1475, name: "Kadai Panner", price: 230, restid: 13, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "veg gravy" },
    { id: 1476, name: "Caswenuut Panner", price: 240, restid: 13, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "veg gravy" },
    { id: 1477, name: "Panner Steam", price: 240, restid: 13, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "veg gravy" },
    { id: 1478, name: "Palak Panner", price: 240, restid: 13, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "veg gravy" },
    { id: 1479, name: "Plain Palak", price: 180, restid: 13, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "veg gravy" },
    { id: 1480, name: "Baby Corn Masala", price: 220, restid: 13, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "veg gravy" },
    { id: 1481, name: "Mashroom Masala", price: 230, restid: 13, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "veg gravy" },
    { id: 1482, name: "Kadai Mashroom", price: 230, restid: 13, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "veg gravy" },
    { id: 1483, name: "Cashwenuut Curry", price: 220, restid: 13, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "veg gravy" },
    { id: 1484, name: "Malai Koftha", price: 230, restid: 13, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "veg gravy" },
    { id: 1485, name: "Stuffed Aloo", price: 200, restid: 13, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "veg gravy" },
    { id: 1486, name: "Veg-Jaipuri", price: 210, restid: 13, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "veg gravy" },
    { id: 1487, name: "Veg Shahi Kurma", price: 220, restid: 13, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "veg gravy" },
    { id: 1488, name: "Veg Kollapuri", price: 220, restid: 13, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "veg gravy" },
    { id: 1489, name: "Methi Chaman", price: 230, restid: 13, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "veg gravy" },
    { id: 1490, name: "Gobi Masala", price: 210, restid: 13, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "veg gravy" },
    { id: 1491, name: "Mix-Veg-Curry", price: 210, restid: 13, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "veg gravy" },
    { id: 1492, name: "Stuffed Capiscum", price: 210, restid: 13, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "veg gravy" },
    { id: 1493, name: "Tomato Curry", price: 180, restid: 13, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "veg gravy" },
    //veg tandoori
    { id: 1494, name: "Panner Tikka", price: 290, restid: 13, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "veg tandoori" },
    { id: 1495, name: "Panner Achari Tikka", price: 290, restid: 13, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "veg tandoori" },
    //roti's
    { id: 1496, name: "Pulka", price: 20, restid: 13, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "roti's" },
    { id: 1497, name: "Chapathi", price: 30, restid: 13, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "roti's" },
    { id: 1498, name: "Parota", price: 25, restid: 13, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "roti's" },
    { id: 1499, name: "Egg Parota", price: 100, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "roti's" },
    { id: 1500, name: "Cylon Parota", price: 60, restid: 13, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "roti's" },
    { id: 1501, name: "Parota (Parcel)", price: 30, restid: 13, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "roti's" },
    { id: 1502, name: "Tandoori Roti", price: 30, restid: 13, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "roti's" },
    { id: 1503, name: "Rumali Roti", price: 60, restid: 13, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "roti's" },
    { id: 1504, name: "Butter Naan", price: 40, restid: 13, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "roti's" },
    { id: 1505, name: "Plain Naan", price: 35, restid: 13, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "roti's" },
    { id: 1506, name: "Plain Kulcha", price: 50, restid: 13, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "roti's" },
    { id: 1507, name: "Butter Kulcha", price: 60, restid: 13, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "roti's" },
    { id: 1508, name: "Aloo Parota", price: 50, restid: 13, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "roti's" },
    { id: 1509, name: "Butter Parota", price: 60, restid: 13, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "roti's" },
    { id: 1510, name: "Garlic Parota", price: 60, restid: 13, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "roti's" },
    { id: 1511, name: "Methi Parota", price: 60, restid: 13, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "roti's" },
    { id: 1512, name: "Garlic Naan", price: 60, restid: 13, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "roti's" },
    { id: 1513, name: "Pudena Parota", price: 60, restid: 13, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "roti's" },
    { id: 1514, name: "Masala Kulcha", price: 80, restid: 13, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "roti's" },
    //egg dry & Gray
    { id: 1515, name: "Omlet", price: 50, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "egg dry & Gray" },
    { id: 1516, name: "Egg 65", price: 170, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "egg dry & Gray" },
    { id: 1517, name: "Egg Buruju", price: 160, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "egg dry & Gray" },
    { id: 1518, name: "Egg Chilly", price: 170, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "egg dry & Gray" },
    { id: 1519, name: "Egg Manchuria", price: 170, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "egg dry & Gray" },
    { id: 1520, name: "Egg Roast", price: 170, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "egg dry & Gray" },
    { id: 1521, name: "Egg Curry", price: 150, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "egg dry & Gray" },
    { id: 1522, name: "Egg Masala", price: 170, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "egg dry & Gray" },
    { id: 1523, name: "Egg Tomato", price: 170, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "egg dry & Gray" },
    { id: 1524, name: "Boiled Egg", price: 15, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "egg dry & Gray" },
    //papads5
    { id: 1525, name: "Masala Papad", price: 70, restid: 13, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "papads5" },
    { id: 1526, name: "Roasted Papad", price: 70, restid: 13, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "papads5" },
    //veg rice
    { id: 1527, name: "Veg Fried Rice", price: 190, restid: 13, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "veg rice" },
    { id: 1528, name: "Paneer Fried Rice", price: 230, restid: 13, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "veg rice" },
    { id: 1529, name: "Mushroom Fried Rice", price: 230, restid: 13, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "veg rice" },
    { id: 1530, name: "Jeera Fried Rice", price: 200, restid: 13, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "veg rice" },
    { id: 1531, name: "Gobi Fried Rice", price: 190, restid: 13, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "veg rice" },
    { id: 1532, name: "Cashew Nut Fried Rice", price: 240, restid: 13, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "veg rice" },
    { id: 1533, name: "Schezwan Fried Rice", price: 240, restid: 13, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "veg rice" },
    { id: 1534, name: "Veg Biryani", price: 200, restid: 13, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "veg rice" },
    { id: 1535, name: "Curd Rice", price: 90, restid: 13, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "veg rice" },
    //Non-veg starters
    { id: 1536, name: "Chicken 65", price: 280, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "Non-veg starters" },
    { id: 1537, name: "Chicken Chilly", price: 280, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "Non-veg starters" },
    { id: 1538, name: "Chicken Manchuria", price: 280, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "Non-veg starters" },
    { id: 1539, name: "Chicken Basket", price: 300, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "Non-veg starters" },
    { id: 1540, name: "Chicken 555", price: 320, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "Non-veg starters" },
    { id: 1541, name: "Erari Chicken", price: 320, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "Non-veg starters" },
    { id: 1542, name: "Pepper Chicken", price: 300, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "Non-veg starters" },
    { id: 1543, name: "Chicken Lemon", price: 300, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "Non-veg starters" },
    { id: 1544, name: "Chicken Rayalaseema (Dry)", price: 300, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "Non-veg starters" },
    { id: 1545, name: "Chicken Dopyaza", price: 300, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "Non-veg starters" },
    { id: 1546, name: "Chicken Lollipop", price: 350, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "Non-veg starters" },
    { id: 1547, name: "Chicken Drumsticks", price: 330, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "Non-veg starters" },
    { id: 1548, name: "Chicken Garlic", price: 300, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "Non-veg starters" },
    { id: 1549, name: "Chicken Majestic", price: 330, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "Non-veg starters" },
    { id: 1550, name: "Chicken Schezwan", price: 330, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "Non-veg starters" },
    { id: 1551, name: "Hindustan Spl Chicken (Dry)", price: 350, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "Non-veg starters" },
    { id: 1552, name: "Ginger Chicken", price: 330, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "Non-veg starters" },
    { id: 1553, name: "Chicken Bourani", price: 330, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "Non-veg starters" },
    { id: 1554, name: "Chicken Shangrilla", price: 330, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "Non-veg starters" },
    { id: 1555, name: "Chicken Spl Roast", price: 330, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "Non-veg starters" },
    { id: 1556, name: "Cashew Nut Chicken", price: 350, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "Non-veg starters" },
    { id: 1557, name: "Chicken Kondatom", price: 330, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "Non-veg starters" },
    { id: 1558, name: "Chicken Gulzor", price: 330, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "Non-veg starters" },
    { id: 1559, name: "Chicken Pataka", price: 330, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "Non-veg starters" },
    { id: 1560, name: "Hindustan Fried Chicken", price: 330, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "Non-veg starters" },
    { id: 1561, name: "Chicken Chocobar", price: 350, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "Non-veg starters" },
    { id: 1562, name: "Chicken Sp Pataka", price: 330, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "Non-veg starters" },
    { id: 1563, name: "Bull Bull Chicken", price: 350, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "Non-veg starters" },
    { id: 1564, name: "Chicken Pondicherry", price: 350, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "Non-veg starters" },
    //Chicken gravy
    { id: 1565, name: "Chicken Andhra", price: 250, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "Chicken gravy" },
    { id: 1566, name: "Butter Chicken", price: 250, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "Chicken gravy" },
    { id: 1567, name: "Ginger Chicken Gravy", price: 260, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "Chicken gravy" },
    { id: 1568, name: "Methi Chicken", price: 260, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "Chicken gravy" },
    { id: 1569, name: "Chicken Asiyana", price: 260, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "Chicken gravy" },
    { id: 1570, name: "Chicken Rayalaseema", price: 250, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "Chicken gravy" },
    { id: 1571, name: "Chicken Kollapuri", price: 250, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "Chicken gravy" },
    { id: 1572, name: "Chicken Jaipuri", price: 270, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "Chicken gravy" },
    { id: 1573, name: "Garlic Chicken", price: 260, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "Chicken gravy" },
    { id: 1574, name: "Chicken Shahi Kurma", price: 250, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "Chicken gravy" },
    { id: 1575, name: "Chicken Hyderabad", price: 250, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "Chicken gravy" },
    { id: 1576, name: "Chicken Tangidi Masala (2pcs)", price: 260, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "Chicken gravy" },
    { id: 1577, name: "Achari Chicken", price: 270, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "Chicken gravy" },
    { id: 1578, name: "Chicken Maharani", price: 260, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "Chicken gravy" },
    { id: 1579, name: "Chicken Mandakini", price: 260, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "Chicken gravy" },
    { id: 1580, name: "Chicken Nawabi", price: 260, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "Chicken gravy" },
    { id: 1581, name: "Chicken Chatpat", price: 270, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "Chicken gravy" },
    { id: 1582, name: "Chicken Afghani", price: 270, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "Chicken gravy" },
    { id: 1583, name: "Kadai Chicken", price: 260, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "Chicken gravy" },
    { id: 1584, name: "Chicken Hundi", price: 270, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "Chicken gravy" },
    { id: 1585, name: "Chicken Punjabi (Bone)", price: 270, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "Chicken gravy" },
    { id: 1586, name: "Nizami Hundi (Bone)", price: 280, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "Chicken gravy" },
    { id: 1587, name: "Chicken Haryali", price: 280, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "Chicken gravy" },
    { id: 1588, name: "Chicken Mughlai", price: 270, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "Chicken gravy" },
    { id: 1589, name: "Chicken Digital", price: 270, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "Chicken gravy" },
    { id: 1590, name: "Chicken Rasheeda", price: 270, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "Chicken gravy" },
    { id: 1591, name: "Cashew Nut Chicken Gravy", price: 280, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "Chicken gravy" },
    { id: 1592, name: "Chicken Kanthari", price: 280, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "Chicken gravy" },
    { id: 1593, name: "Chicken Tikka Masala", price: 290, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "Chicken gravy" },
    { id: 1594, name: "Chicken Chameli", price: 290, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "Chicken gravy" },
    { id: 1595, name: "Hindustan Special Chicken", price: 300, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "Chicken gravy" },
    //mutton dry
    { id: 1596, name: "Mutton Roast", price: 380, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "mutton dry" },
    { id: 1597, name: "Mutton Chilly", price: 350, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "mutton dry" },
    { id: 1598, name: "Mutton Manchuria", price: 350, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "mutton dry" },
    { id: 1599, name: "Mutton 65", price: 350, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "mutton dry" },
    { id: 1600, name: "Schezwan Mutton", price: 380, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "mutton dry" },
    //mutton Gravy
    { id: 1601, name: "Mutton Tawa Ghost", price: 350, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "mutton Gravy" },
    { id: 1602, name: "Mutton Curry", price: 350, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "mutton Gravy" },
    { id: 1603, name: "Mutton Masala", price: 350, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "mutton Gravy" },
    { id: 1604, name: "Mutton Ginger", price: 350, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "mutton Gravy" },
    { id: 1605, name: "Methi Mutton", price: 360, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "mutton Gravy" },
    { id: 1606, name: "Mutton Rayalaseema", price: 350, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "mutton Gravy" },
    { id: 1607, name: "Kadai Mutton", price: 350, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "mutton Gravy" },
    { id: 1608, name: "Hindustan Special Mutton", price: 380, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "mutton Gravy" },
    //sea food
    { id: 1609, name: "Fish 65", price: 290, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "sea food" },
    { id: 1610, name: "Fish Chilly", price: 290, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "sea food" },
    { id: 1611, name: "Apollo Fish", price: 290, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "sea food" },
    { id: 1612, name: "Fish Manchuria", price: 290, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "sea food" },
    { id: 1613, name: "Fish Basket", price: 290, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "sea food" },
    { id: 1614, name: "Fish Curry", price: 290, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "sea food" },
    { id: 1615, name: "Prawns Manchuria", price: 320, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "sea food" },
    { id: 1616, name: "Prawns 65", price: 320, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "sea food" },
    { id: 1617, name: "Prawns Chilly", price: 320, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "sea food" },
    { id: 1618, name: "Loose Prawns", price: 320, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "sea food" },
    { id: 1619, name: "Prawns Curry", price: 320, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "sea food" },
    //non veg tandoori
    { id: 1620, name: "Chicken Tikka", price: 300, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "non veg tandoori" },
    { id: 1621, name: "Chicken Reshmi Kebab", price: 300, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "non veg tandoori" },
    { id: 1622, name: "Chicken Malai Kebab", price: 300, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "non veg tandoori" },
    { id: 1623, name: "Chicken Tangdi Kebab (3pcs)", price: 280, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "non veg tandoori" },
    { id: 1624, name: "Tandoori Chicken (Half)", price: 320, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "non veg tandoori" },
    { id: 1625, name: "Tandoori Chicken (Full)", price: 600, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "non veg tandoori" },
    { id: 1626, name: "Fish Tikka", price: 280, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "non veg tandoori" },
    //non veg rice
    { id: 1627, name: "Egg Fried Rice", price: 190, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "non veg rice" },
    { id: 1628, name: "Chicken Fried Rice", price: 250, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "non veg rice" },
    { id: 1629, name: "Chicken Schezwan Fried Rice", price: 260, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "non veg rice" },
    { id: 1630, name: "Prawns Fried Rice", price: 300, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "non veg rice" },
    { id: 1631, name: "Fish Fried Rice", price: 300, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "non veg rice" },
    // Biryani
    { id: 1632, name: "Special Chicken Biryani", price: 280, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "Biryani" },
    { id: 1633, name: "Special Chicken Biryani (Roast)", price: 300, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "Biryani" },
    { id: 1634, name: "Chicken Dum Biryani", price: 220, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "Biryani" },
    { id: 1635, name: "Mutton Biryani", price: 400, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "Biryani" },
    { id: 1636, name: "Fish Biryani", price: 320, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "Biryani" },
    { id: 1637, name: "Egg Biryani", price: 200, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "Biryani" },
    { id: 1638, name: "Biryani Rice", price: 170, restid: 13, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "Biryani" },
    { id: 1639, name: "Prawns Biryani", price: 330, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "Biryani" },
    { id: 1640, name: "Chicken Tangdi Biryani", price: 300, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "Biryani" },
    { id: 1641, name: "Chicken Tandoori Biryani", price: 300, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "Biryani" },
    { id: 1642, name: "Royal Chicken Biryani", price: 550, restid: 13, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "Biryani" },
    //ice creams
    { id: 1643, name: "Vanilla Ice Cream (Single Scoop)", price: 60, restid: 13, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "ice creams" },
    { id: 1644, name: "Strawberry Ice Cream (Single Scoop)", price: 60, restid: 13, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "ice creams" },
    { id: 1645, name: "Butterscotch Ice Cream (Single Scoop)", price: 70, restid: 13, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "ice creams" },
    { id: 1646, name: "Chocolate Ice Cream (Single Scoop)", price: 70, restid: 13, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "ice creams" },
    { id: 1647, name: "Black Currant Ice Cream (Single Scoop)", price: 80, restid: 13, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "ice creams" },
    { id: 1648, name: "Honey Almond Ice Cream (Single Scoop)", price: 80, restid: 13, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "ice creams" },
    { id: 1649, name: "Anjeer Badam Ice Cream (Single Scoop)", price: 80, restid: 13, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "ice creams" },
    { id: 1650, name: "Caramel Nuts Ice Cream (Single Scoop)", price: 100, restid: 13, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "ice creams" },
    { id: 1651, name: "Belgian Dark Chocolate Ice Cream (Single Scoop)", price: 100, restid: 13, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "ice creams" },

]