export const Data = [


    //veg starters
    { "id": 1377, "name": "Corn Cheese Cookets", "price": 320, "restid": 12, "button": "Add", "type": "veg", "symbol": "🟩", "category": "veg-starters", "image": "/fooditems/1 (362).webp" },
    { "id": 1378, "name": "Rayalaseema Paneer Vepudu", "price": 320, "restid": 12, "button": "Add", "type": "veg", "symbol": "🟩", "category": "veg-starters", "image": "/fooditems/1 (363).webp" },
    { "id": 1379, "name": "Golden Fried Baby Corn", "price": 300, "restid": 12, "button": "Add", "type": "veg", "symbol": "🟩", "category": "veg-starters", "image": "/fooditems/1 (364).webp" },
    { "id": 1380, "name": "Salt and Pepper Mushroom", "price": 320, "restid": 12, "button": "Add", "type": "veg", "symbol": "🟩", "category": "veg-starters", "image": "/fooditems/1 (365).webp" },
    { "id": 1381, "name": "Dragon Gobi", "price": 270, "restid": 12, "button": "Add", "type": "veg", "symbol": "🟩", "category": "veg-starters", "image": "/fooditems/1 (366).webp" },
    { "id": 1382, "name": "Gobi 65", "price": 270, "restid": 12, "button": "Add", "type": "veg", "symbol": "🟩", "category": "veg-starters", "image": "/fooditems/1 (367).webp" },
    { "id": 1383, "name": "Dragon Paneer", "price": 320, "restid": 12, "button": "Add", "type": "veg", "symbol": "🟩", "category": "veg-starters", "image": "/fooditems/1 (368).webp" },
    { "id": 1384, "name": "Malai Paneer Tikka", "price": 340, "restid": 12, "button": "Add", "type": "veg", "symbol": "🟩", "category": "veg-starters", "image": "/fooditems/1 (369).webp" },
    { "id": 1385, "name": "Paneer Majestic", "price": 320, "restid": 12, "button": "Add", "type": "veg", "symbol": "🟩", "category": "veg-starters", "image": "/fooditems/1 (370).webp" },
    { "id": 1386, "name": "Paneer Tikka", "price": 340, "restid": 12, "button": "Add", "type": "veg", "symbol": "🟩", "category": "veg-starters", "image": "/fooditems/1 (371).webp" },
    { "id": 1387, "name": "Veg Manchurian", "price": 270, "restid": 12, "button": "Add", "type": "veg", "symbol": "🟩", "category": "veg-starters", "image": "/fooditems/1 (372).webp" },
    { "id": 1388, "name": "Ragi Mudda", "price": 120, "restid": 12, "button": "Add", "type": "veg", "symbol": "🟩", "category": "veg-starters", "image": "/fooditems/1 (373).webp" },
    { "id": 1389, "name": "Kaju Fried Rice", "price": 270, "restid": 12, "button": "Add", "type": "veg", "symbol": "🟩", "category": "veg-starters", "image": "/fooditems/1 (374).webp" },
    //Authentic Non Veg Starters
    { "id": 1390, "name": "Mallikas Special Homestyle Chicken Fry", "price": 320, "restid": 12, "button": "Add", "type": "non-veg", "symbol": "🟥", "category": "authentic-non-veg-starters", "image": "/fooditems/1 (375).webp" },
    { "id": 1391, "name": "Chicken Ghee Roast", "price": 320, "restid": 12, "button": "Add", "type": "non-veg", "symbol": "🟥", "category": "authentic-non-veg-starters", "image": "/fooditems/1 (376).webp" },
    { "id": 1392, "name": "Vellulli Karam Kodi Vepudu", "price": 300, "restid": 12, "button": "Add", "type": "non-veg", "symbol": "🟥", "category": "authentic-non-veg-starters", "image": "/fooditems/1 (377).webp" },
    { "id": 1393, "name": "Mutton Ghee Roast", "price": 520, "restid": 12, "button": "Add", "type": "non-veg", "symbol": "🟥", "category": "authentic-non-veg-starters", "image": "/fooditems/1 (378).webp" },
    { "id": 1394, "name": "Koramenu Chepa Fry", "price": 480, "restid": 12, "button": "Add", "type": "non-veg", "symbol": "🟥", "category": "authentic-non-veg-starters", "image": "/fooditems/1 (379).webp" },
    { "id": 1395, "name": "Nellore Royyala Vepudu", "price": 400, "restid": 12, "button": "Add", "type": "non-veg", "symbol": "🟥", "category": "authentic-non-veg-starters", "image": "/fooditems/1 (380).webp" },
    { "id": 1396, "name": "Finger Prawns", "price": 420, "restid": 12, "button": "Add", "type": "non-veg", "symbol": "🟥", "category": "authentic-non-veg-starters", "image": "/fooditems/1 (381).webp" },
    //Regular Non Veg Starters
    { "id": 1397, "name": "Chilli Egg", "price": 230, "restid": 12, "button": "Add", "type": "non-veg", "symbol": "🟥", "category": "regular-non-veg-starters", "image": "/fooditems/1 (382).webp" },
    { "id": 1398, "name": "Chicken Majestic", "price": 350, "restid": 12, "button": "Add", "type": "non-veg", "symbol": "🟥", "category": "regular-non-veg-starters", "image": "/fooditems/1 (383).webp" },
    { "id": 1399, "name": "Chicken Lollipop", "price": 360, "restid": 12, "button": "Add", "type": "non-veg", "symbol": "🟥", "category": "regular-non-veg-starters", "image": "/fooditems/1 (384).webp" },
    { "id": 1400, "name": "Chilli Chicken", "price": 340, "restid": 12, "button": "Add", "type": "non-veg", "symbol": "🟥", "category": "regular-non-veg-starters", "image": "/fooditems/1 (385).webp" },
    { "id": 1401, "name": "Chicken 65", "price": 340, "restid": 12, "button": "Add", "type": "non-veg", "symbol": "🟥", "category": "regular-non-veg-starters", "image": "/fooditems/1 (386).webp" },
    { "id": 1402, "name": "Loose Prawns", "price": 380, "restid": 12, "button": "Add", "type": "non-veg", "symbol": "🟥", "category": "regular-non-veg-starters", "image": "/fooditems/1 (387).webp" },
    //Tandoori Non Veg Starters
    { "id": 1403, "name": "Murg Malai Kebab", "price": 430, "restid": 12, "button": "Add", "type": "non-veg", "symbol": "🟥", "category": "tandoori-non-veg-starters", "image": "/fooditems/1 (388).webp" },
    { "id": 1404, "name": "Tandoori Chicken", "price": 430, "restid": 12, "button": "Add", "type": "non-veg", "symbol": "🟥", "category": "tandoori-non-veg-starters", "image": "/fooditems/1 (389).webp" },
    { "id": 1405, "name": "Acharya Chicken Kebab", "price": 420, "restid": 12, "button": "Add", "type": "non-veg", "symbol": "🟥", "category": "tandoori-non-veg-starters", "image": "/fooditems/1 (390).webp" },
    //veg-main-course
    { "id": 1406, "name": "Kaju Mushroom Curry", "price": 320, "restid": 12, "button": "Add", "type": "veg", "symbol": "🟩", "category": "veg-main-course", "image": "/fooditems/1 (391).webp" },
    { "id": 1407, "name": "Kaju Tomato Curry", "price": 300, "restid": 12, "button": "Add", "type": "veg", "symbol": "🟩", "category": "veg-main-course", "image": "/fooditems/1 (392).webp" },
    { "id": 1408, "name": "Methi Chaman Kura", "price": 320, "restid": 12, "button": "Add", "type": "veg", "symbol": "🟩", "category": "veg-main-course", "image": "/fooditems/1 (393).webp" },
    { "id": 1409, "name": "Mushroom Masala Curry", "price": 290, "restid": 12, "button": "Add", "type": "veg", "symbol": "🟩", "category": "veg-main-course", "image": "/fooditems/1 (394).webp" },
    { "id": 1410, "name": "Restuarant Special Guttivankaya Kura", "price": 220, "restid": 12, "button": "Add", "type": "veg", "symbol": "🟩", "category": "veg-main-course", "image": "/fooditems/1 (395).webp" },
    { "id": 1411, "name": "Veg Chatpat", "price": 252, "restid": 12, "button": "Add", "type": "veg", "symbol": "🟩", "category": "veg-main-course", "image": "/fooditems/1 (396).webp" },
    { "id": 1412, "name": "Dal Tadka", "price": 240, "restid": 12, "button": "Add", "type": "veg", "symbol": "🟩", "category": "veg-main-course", "image": "/fooditems/1 (397).webp" },
    { "id": 1413, "name": "Kadai Veg", "price": 264, "restid": 12, "button": "Add", "type": "veg", "symbol": "🟩", "category": "veg-main-course", "image": "/fooditems/1 (398).webp" },
    { "id": 1414, "name": "Paneer Butter Masala", "price": 312, "restid": 12, "button": "Add", "type": "veg", "symbol": "🟩", "category": "veg-main-course", "image": "/fooditems/1 (399).webp" },
    //Non-veg-main-course
    { "id": 1415, "name": "Butter Chicken Masala", "price": 336, "restid": 12, "button": "Add", "type": "non-veg", "symbol": "🟥", "category": "non-veg-main-course", "image": "/fooditems/1 (400).webp" },
    { "id": 1416, "name": "Gongura Chicken Curry", "price": 336, "restid": 12, "button": "Add", "type": "non-veg", "symbol": "🟥", "category": "non-veg-main-course", "image": "/fooditems/1 (401).webp" },
    { "id": 1417, "name": "Haradaniya Chicken Curry", "price": 350, "restid": 12, "button": "Add", "type": "non-veg", "symbol": "🟥", "category": "non-veg-main-course", "image": "/fooditems/1 (402).webp" },
    { "id": 1418, "name": "Kadhai Chicken", "price": 340, "restid": 12, "button": "Add", "type": "non-veg", "symbol": "🟥", "category": "non-veg-main-course", "image": "/fooditems/1 (403).webp" },
    { "id": 1419, "name": "Egg Masala", "price": 220, "restid": 12, "button": "Add", "type": "non-veg", "symbol": "🟥", "category": "non-veg-main-course", "image": "/fooditems/1 (404).webp" },
    { "id": 1420, "name": "Home Style Chicken Curry", "price": 340, "restid": 12, "button": "Add", "type": "non-veg", "symbol": "🟥", "category": "non-veg-main-course", "image": "/fooditems/1 (405).webp" },
    { "id": 1421, "name": "Mallikas Special Natukodi Pulusu", "price": 540, "restid": 12, "button": "Add", "type": "non-veg", "symbol": "🟥", "category": "non-veg-main-course", "image": "/fooditems/1 (406).webp" },
    { "id": 1422, "name": "Rayalaseema Kodi Kura", "price": 336, "restid": 12, "button": "Add", "type": "non-veg", "symbol": "🟥", "category": "non-veg-main-course", "image": "/fooditems/1 (407).webp" },
    { "id": 1423, "name": "Inti Style Mutton Kura", "price": 540, "restid": 12, "button": "Add", "type": "non-veg", "symbol": "🟥", "category": "non-veg-main-course", "image": "/fooditems/1 (408).webp" },
    { "id": 1424, "name": "Egg Bhurji", "price": 170, "restid": 12, "button": "Add", "type": "non-veg", "symbol": "🟥", "category": "non-veg-main-course", "image": "/fooditems/1 (409).webp" },
    //Breads
    { "id": 1425, "name": "Plain Naan", "price": 50, "restid": 12, "button": "Add", "type": "veg", "symbol": "🟩", "category": "breads", "image": "/fooditems/1 (410).webp" },
    { "id": 1426, "name": "Butter Naan", "price": 55, "restid": 12, "button": "Add", "type": "veg", "symbol": "🟩", "category": "breads", "image": "/fooditems/1 (411).webp" },
    { "id": 1427, "name": "Garlic Naan", "price": 65, "restid": 12, "button": "Add", "type": "veg", "symbol": "🟩", "category": "breads", "image": "/fooditems/1 (412).webp" },
    { "id": 1428, "name": "Plain Tandoori Roti", "price": 40, "restid": 12, "button": "Add", "type": "veg", "symbol": "🟩", "category": "breads", "image": "/fooditems/1 (413).webp" },
    { "id": 1429, "name": "Butter Tandoori Roti", "price": 45, "restid": 12, "button": "Add", "type": "veg", "symbol": "🟩", "category": "breads", "image": "/fooditems/1 (414).webp" },
    //Pulaos-rice
    { "id": 1430, "name": "Perugu Annam Thalimpu", "price": 140, "restid": 12, "button": "Add", "type": "veg", "symbol": "🟩", "category": "pulaos-rice", "image": "/fooditems/1 (415).webp" },
    { "id": 1431, "name": "Veg Pulao", "price": 220, "restid": 12, "button": "Add", "type": "veg", "symbol": "🟩", "category": "pulaos-rice", "image": "/fooditems/1 (416).webp" },
    { "id": 1432, "name": "Egg Pulao", "price": 240, "restid": 12, "button": "Add", "type": "non-veg", "symbol": "🟥", "category": "pulaos-rice", "image": "/fooditems/1 (417).webp" },
    { "id": 1433, "name": "Fry Piece Kodi Pulao", "price": 340, "restid": 12, "button": "Add", "type": "non-veg", "symbol": "🟥", "category": "pulaos-rice", "image": "/fooditems/1 (418).webp" },
    { "id": 1434, "name": "Mutton Fry Piece Pulao", "price": 520, "restid": 12, "button": "Add", "type": "non-veg", "symbol": "🟥", "category": "pulaos-rice", "image": "/fooditems/1 (419).webp" },
    { "id": 1435, "name": "Royyala Vepudu Pulao", "price": 440, "restid": 12, "button": "Add", "type": "non-veg", "symbol": "🟥", "category": "pulaos-rice", "image": "/fooditems/1 (420).webp" },
    { "id": 1436, "name": "Gutti Vankaya Pulao", "price": 300, "restid": 12, "button": "Add", "type": "veg", "symbol": "🟩", "category": "pulaos-rice", "image": "/fooditems/1 (421).webp" },
    { "id": 1437, "name": "Ragi Mudda", "price": 120, "restid": 12, "button": "Add", "type": "veg", "symbol": "🟩", "category": "pulaos-rice", "image": "/fooditems/1 (422).webp" },
    //Biryani
    { "id": 1438, "name": "Pachimirchi Paneer paluo", "price": 300, "restid": 12, "button": "Add", "type": "veg", "symbol": "🟩", "category": "biryani", "image": "/fooditems/1 (423).webp" },
    { "id": 1439, "name": "Paneer paluo", "price": 300, "restid": 12, "button": "Add", "type": "veg", "symbol": "🟩", "category": "biryani", "image": "/fooditems/1 (424).webp" },
    { "id": 1440, "name": "Egg Biryani [2 Eggs]", "price": 240, "restid": 12, "button": "Add", "type": "non-veg", "symbol": "🟥", "category": "biryani", "image": "/fooditems/1 (425).webp" },
    { "id": 1441, "name": "Kurnool Chicken Dum Biryani", "price": 360, "restid": 12, "button": "Add", "type": "non-veg", "symbol": "🟥", "category": "biryani", "image": "/fooditems/1 (426).webp" },
    { "id": 1442, "name": "Special Chicken Biryani", "price": 370, "restid": 12, "button": "Add", "type": "non-veg", "symbol": "🟥", "category": "biryani", "image": "/fooditems/1 (427).webp" },
    { "id": 1443, "name": "KTR Mutton Dum Biryani Restaurant Special", "price": 520, "restid": 12, "button": "Add", "type": "non-veg", "symbol": "🟥", "category": "biryani", "image": "/fooditems/1 (428).webp" },
    { "id": 1444, "name": "Mutton Fry Piece Biryani", "price": 520, "restid": 12, "button": "Add", "type": "non-veg", "symbol": "🟥", "category": "biryani", "image": "/fooditems/1 (429).webp" },
    { "id": 1445, "name": "Chicken Fry Piece Biryani", "price": 360, "restid": 12, "button": "Add", "type": "non-veg", "symbol": "🟥", "category": "biryani", "image": "/fooditems/1 (430).webp" },
    { "id": 1446, "name": "Kurnool Chicken Dum Biryani [Family Pack]", "price": 750, "restid": 12, "button": "Add", "type": "non-veg", "symbol": "🟥", "category": "biryani", "image": "/fooditems/1 (431).webp" },
    { "id": 1447, "name": "Hyderabadi Mutton Dum Biryani", "price": 520, "restid": 12, "button": "Add", "type": "non-veg", "symbol": "🟥", "category": "biryani", "image": "/fooditems/1 (432).webp" },
    //Fried-rice
    { "id": 1448, "name": "Mushroom Fried Rice", "price": 280, "restid": 12, "button": "Add", "type": "veg", "symbol": "🟩", "category": "fried-rice", "image": "/fooditems/1 (433).webp" },
    { "id": 1449, "name": "Paneer Fried Rice", "price": 280, "restid": 12, "button": "Add", "type": "veg", "symbol": "🟩", "category": "fried-rice", "image": "/fooditems/1 (434).webp" },
    { "id": 1450, "name": "Veg Fried Rice", "price": 220, "restid": 12, "button": "Add", "type": "veg", "symbol": "🟩", "category": "fried-rice", "image": "/fooditems/1 (435).webp" },
    { "id": 1451, "name": "Egg Fried Rice", "price": 220, "restid": 12, "button": "Add", "type": "non-veg", "symbol": "🟥", "category": "fried-rice", "image": "/fooditems/1 (436).webp" },
    { "id": 1452, "name": "Chicken Fried Rice", "price": 325, "restid": 12, "button": "Add", "type": "non-veg", "symbol": "🟥", "category": "fried-rice", "image": "/fooditems/1 (437).webp" },


]