export const Data = [

  //////////    PR GRAND 

  { id: 725, name: "Gobi Manchuria", price: 180, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (68).webp", category: "veg starters" },
  { id: 726, name: "Gobi 65", price: 180, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (69).webp", category: "veg starters" },
  { id: 727, name: "Gobi Chilly", price: 180, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (70).webp", category: "veg starters" },
  { id: 728, name: "Gobi Pepper", price: 180, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (71).webp", category: "veg starters" },
  { id: 729, name: "Paneer Chilly", price: 200, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (72).webp", category: "veg starters" },
  { id: 730, name: "Paneer Manchuria", price: 200, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (73).webp", category: "veg starters" },
  { id: 731, name: "Veg Manchuria", price: 200, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (74).webp", category: "veg starters" },
  { id: 732, name: "Mushroom Chilly", price: 210, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (75).webp", category: "veg starters" },
  { id: 733, name: "Mushroom solden", price: 210, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (76).webp", category: "veg starters" },
  { id: 734, name: "Mushroom solden And Pepper", price: 210, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (77).webp", category: "veg starters" },
  { id: 735, name: "Pepper Mushroom", price: 210, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (78).webp", category: "veg starters" },
  { id: 736, name: "Mushroom Manchuria", price: 210, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (79).webp", category: "veg starters" },
  { id: 737, name: "Baby Corn Chilly", price: 170, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (80).webp", category: "veg starters" },
  { id: 738, name: "Baby Corn 65", price: 200, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (81).webp", category: "veg starters" },
  { id: 739, name: "Baby Corn Sismiss Fry", price: 220, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (82).webp", category: "veg starters" },
  { id: 740, name: "Veg Basket", price: 200, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (83).webp", category: "veg starters" },
  { id: 741, name: "Paneer 65", price: 200, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (84).webp", category: "veg starters" },
  { id: 742, name: "Kaju Paneer", price: 200, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (85).webp", category: "veg starters" },
  { id: 743, name: "Veg Shangrila", price: 220, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (86).webp", category: "veg starters" },
  { id: 744, name: "Golden Paneer", price: 210, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (87).webp", category: "veg starters" },
  { id: 745, name: "Dragon Paneer", price: 220, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (88).webp", category: "veg starters" },

  //non-veg starters
  { id: 746, name: "Chicken 65", price: 260, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (89).webp", category: "non-veg starters" },
  { id: 747, name: "Chicken 555", price: 260, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (90).webp", category: "non-veg starters" },
  { id: 748, name: "Chicken Majestic", price: 260, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (91).webp", category: "non-veg starters" },
  { id: 749, name: "Chicken Manchuria", price: 260, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (92).webp", category: "non-veg starters" },
  { id: 750, name: "Chicken Dragon", price: 270, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (93).webp", category: "non-veg starters" },
  { id: 751, name: "Chicken Lemon", price: 250, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (94).webp", category: "non-veg starters" },
  { id: 752, name: "Chicken Chilly", price: 260, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (95).webp", category: "non-veg starters" },
  { id: 753, name: "Chicken Lollipop (6 pcs)", price: 260, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (96).webp", category: "non-veg starters" },
  { id: 754, name: "Chicken Pepper", price: 260, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (97).webp", category: "non-veg starters" },
  { id: 755, name: "Garlic Chicken", price: 260, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (98).webp", category: "non-veg starters" },
  { id: 756, name: "Kaju Chicken", price: 270, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (99).webp", category: "non-veg starters" },
  { id: 757, name: "Chicken Sezwan", price: 260, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (100).webp", category: "non-veg starters" },
  { id: 758, name: "Chicken Drumsticks (6 pcs)", price: 260, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (101).webp", category: "non-veg starters" },
  { id: 759, name: "Chicken Shangrila", price: 270, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (102).webp", category: "non-veg starters" },
  { id: 760, name: "Chicken Pataka", price: 280, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (103).webp", category: "non-veg starters" },
  { id: 761, name: "Chicken Basket", price: 260, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (104).webp", category: "non-veg starters" },
  { id: 762, name: "Ginger Chicken", price: 260, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (105).webp", category: "non-veg starters" },
  { id: 763, name: "Chicken Gulzar", price: 270, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (106).webp", category: "non-veg starters" },
  { id: 764, name: "Hongkong Chicken", price: 270, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (107).webp", category: "non-veg starters" },
  { id: 765, name: "Chicken Burrani", price: 280, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (108).webp", category: "non-veg starters" },
  { id: 766, name: "Natukodi Fry", price: 300, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (109).webp", category: "non-veg starters" },

  //non-veg mouuton
  { id: 767, name: "Mutton 65", price: 320, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (110).webp", category: "non-veg mouuton" },
  { id: 768, name: "Mutton Chilly", price: 320, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (111).webp", category: "non-veg mouuton" },
  { id: 769, name: "Mutton Manchuria", price: 320, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (112).webp", category: "non-veg mouuton" },
  { id: 770, name: "Mutton Pepper", price: 320, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (113).webp", category: "non-veg mouuton" },
  { id: 771, name: "Mutton Roast", price: 320, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (114).webp", category: "non-veg mouuton" },

  //Fastfood
  { id: 772, name: "Egg Noodles", price: 180, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (115).webp", category: "Fastfood" },
  { id: 773, name: "Chicken Noodles", price: 200, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (116).webp", category: "Fastfood" },
  { id: 774, name: "Schezwan Chicken Noodles", price: 200, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (117).webp", category: "Fastfood" },
  { id: 775, name: "Prawns Noodles", price: 220, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (118).webp", category: "Fastfood" },
  { id: 776, name: "Chilli Garlic Chicken Noodles", price: 200, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (119).webp", category: "Fastfood" },
  { id: 777, name: "Mix Non Veg Noodles", price: 200, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (120).webp", category: "Fastfood" },
  { id: 778, name: "Schezwan Egg Noodles", price: 170, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (121).webp", category: "Fastfood" },
  { id: 779, name: "Non Veg Hatka Noodles", price: 200, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (122).webp", category: "Fastfood" },
  { id: 780, name: "Veg Noodles", price: 170, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (123).webp", category: "Fastfood" },
  { id: 781, name: "Paneer Noodles", price: 180, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (124).webp", category: "Fastfood" },
  { id: 782, name: "Schezwan Veg Noodles", price: 180, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (125).webp", category: "Fastfood" },
  { id: 783, name: "Chilli Garlic Veg Noodles", price: 180, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (126).webp", category: "Fastfood" },
  { id: 784, name: "Veg Hatka Noodles", price: 190, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (127).webp", category: "Fastfood" },
  { id: 785, name: "Mushroom Noodles", price: 160, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (128).webp", category: "Fastfood" },

  //fish
  { id: 786, name: "Fish 65", price: 260, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (129).webp", category: "fish" },
  { id: 787, name: "Fish Chilly", price: 260, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (130).webp", category: "fish" },
  { id: 788, name: "Fish Pepper", price: 260, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (131).webp", category: "fish" },
  { id: 789, name: "Apollo Fish", price: 260, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (132).webp", category: "fish" },
  { id: 790, name: "Fish Fry", price: 260, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (133).webp", category: "fish" },
  { id: 791, name: "Finger Fish", price: 260, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (134).webp", category: "fish" },
  { id: 792, name: "Fish Basket", price: 260, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (135).webp", category: "fish" },
  { id: 793, name: "Fish 555", price: 260, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (136).webp", category: "fish" },
  { id: 794, name: "Dragon Fish", price: 260, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (137).webp", category: "fish" },
  { id: 795, name: "Prawns Pepper", price: 280, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (138).webp", category: "fish" },
  { id: 796, name: "Prawns 65", price: 280, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (139).webp", category: "fish" },
  { id: 797, name: "Prawns Chilly", price: 280, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (140).webp", category: "fish" },
  { id: 798, name: "Prawns Manchuria", price: 280, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (141).webp", category: "fish" },
  { id: 799, name: "Loose Prawns", price: 280, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (142).webp", category: "fish" },
  { id: 800, name: "Golden Prawns", price: 280, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (143).webp", category: "fish" },

  //egg
  { id: 801, name: "Egg 65", price: 150, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (144).webp", category: "egg" },
  { id: 802, name: "Egg Chilly", price: 150, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (145).webp", category: "egg" },
  { id: 803, name: "Egg Bhurji", price: 150, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (146).webp", category: "egg" },
  { id: 804, name: "Egg Manchuria", price: 150, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (147).webp", category: "egg" },
  { id: 805, name: "Egg Basket", price: 150, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (148).webp", category: "egg" },
  { id: 806, name: "Boiled Egg (1 pc)", price: 20, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (149).webp", category: "egg" },

  //egg curries
  { id: 807, name: "Egg curry", price: 160, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (150).webp", category: "egg curries" },
  { id: 808, name: "Egg Masala", price: 160, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (151).webp", category: "egg curries" },
  { id: 809, name: "Egg fry", price: 160, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (152).webp", category: "egg curries" },
  { id: 810, name: "Egg Butter", price: 160, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (153).webp", category: "egg curries" },

  //tandoori-veg
  { id: 811, name: "Paneer Tikka", price: 280, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (154).webp", category: "tandoori-veg" },
  { id: 812, name: "Paneer Tranga", price: 290, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (155).webp", category: "tandoori-veg" },
  { id: 813, name: "Veg Seekh Kabab", price: 250, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (156).webp", category: "tandoori-veg" },
  { id: 814, name: "Gobi Tikka", price: 250, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (157).webp", category: "tandoori-veg" },
  { id: 815, name: "Mushroom Tikka", price: 280, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (158).webp", category: "tandoori-veg" },
  { id: 816, name: "Haraburra Kabab", price: 280, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (159).webp", category: "tandoori-veg" },

  //non-vegTandoori & Kababs
  { id: 817, name: "Chicken Tikka", price: 280, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (160).webp", category: "non-vegTandoori & Kababs" },
  { id: 818, name: "Chicken Tandoori (Full)", price: 600, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (161).webp", category: "non-vegTandoori & Kababs" },
  { id: 819, name: "Chicken Tandoori (Half)", price: 300, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (162).webp", category: "non-vegTandoori & Kababs" },
  { id: 820, name: "Tangdi Kabab (Full)", price: 300, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (163).webp", category: "non-vegTandoori & Kababs" },
  { id: 821, name: "Tangdi Kabab (Half)", price: 150, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (164).webp", category: "non-vegTandoori & Kababs" },
  { id: 822, name: "Malai Kabab", price: 315, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (165).webp", category: "non-vegTandoori & Kababs" },
  { id: 823, name: "Reshmi Kabab", price: 315, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (166).webp", category: "non-vegTandoori & Kababs" },
  { id: 824, name: "Garlic Kabab", price: 315, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (167).webp", category: "non-vegTandoori & Kababs" },
  { id: 825, name: "Hyderabadi Kabab", price: 315, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (168).webp", category: "non-vegTandoori & Kababs" },
  { id: 826, name: "Mutton Seekh Kabab", price: 400, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (169).webp", category: "non-vegTandoori & Kababs" },
  { id: 827, name: "Chicken Seekh Kabab", price: 340, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (170).webp", category: "non-vegTandoori & Kababs" },
  { id: 828, name: "Haryani Kabab", price: 315, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (171).webp", category: "non-vegTandoori & Kababs" },

  //veg curries
  { id: 829, name: "Paneer Butter Masala", price: 220, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (172).webp", category: "veg curries" },
  { id: 830, name: "Paneer Sahi Kurma", price: 220, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (173).webp", category: "veg curries" },
  { id: 831, name: "Paneer Do Pyaz", price: 220, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (174).webp", category: "veg curries" },
  { id: 832, name: "Paneer Mutter", price: 220, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (175).webp", category: "veg curries" },
  { id: 833, name: "Paneer Tikka Masala", price: 220, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (176).webp", category: "veg curries" },
  { id: 834, name: "Palak Paneer", price: 220, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (177).webp", category: "veg curries" },
  { id: 835, name: "Kadai Paneer", price: 220, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (178).webp", category: "veg curries" },
  { id: 836, name: "Kaju Paneer Curry", price: 230, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (179).webp", category: "veg curries" },
  { id: 837, name: "Kaju Curry", price: 230, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (180).webp", category: "veg curries" },
  { id: 838, name: "Kaju Masala", price: 230, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (181).webp", category: "veg curries" },
  { id: 839, name: "Mix Veg Curry", price: 200, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (182).webp", category: "veg curries" },
  { id: 840, name: "Plain Palak", price: 180, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (183).webp", category: "veg curries" },
  { id: 841, name: "Methi Chaman", price: 220, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (184).webp", category: "veg curries" },
  { id: 842, name: "Malai Kofta", price: 240, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (185).webp", category: "veg curries" },
  { id: 843, name: "Malai Paneer", price: 220, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (186).webp", category: "veg curries" },
  { id: 844, name: "Veg Kolhapuri", price: 180, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (187).webp", category: "veg curries" },
  { id: 845, name: "Tomato Curry", price: 160, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (188).webp", category: "veg curries" },
  { id: 846, name: "Gobi Masala", price: 160, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (189).webp", category: "veg curries" },
  { id: 847, name: "Veg Bavarchi (SPL)", price: 220, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (190).webp", category: "veg curries" },
  { id: 848, name: "Veg Nawabi (SPL)", price: 220, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (191).webp", category: "veg curries" },
  { id: 849, name: "Aloo Gobi Masala", price: 160, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (192).webp", category: "veg curries" },
  { id: 850, name: "Veg Do Pyaz", price: 170, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (193).webp", category: "veg curries" },
  { id: 851, name: "Veg Hyderabad", price: 180, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (194).webp", category: "veg curries" },
  { id: 852, name: "Mushroom Masala", price: 220, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (195).webp", category: "veg curries" },
  { id: 853, name: "Mushroom Curry", price: 220, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (196).webp", category: "veg curries" },
  { id: 854, name: "Kadi Mushroom", price: 220, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (197).webp", category: "veg curries" },

  //non-veg chicken curries
  { id: 855, name: "Butter Chicken", price: 250, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (198).webp", category: "non-veg chicken curries" },
  { id: 856, name: "Chicken Masala", price: 250, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (199).webp", category: "non-veg chicken curries" },
  { id: 857, name: "Chicken Bawarchi", price: 250, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp", category: "non-veg chicken curries" },
  { id: 858, name: "Chicken Nawabi", price: 260, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (201).webp", category: "non-veg chicken curries" },
  { id: 859, name: "Kadai Chicken", price: 250, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (202).webp", category: "non-veg chicken curries" },
  { id: 860, name: "Chicken Bone Curry", price: 250, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (203).webp", category: "non-veg chicken curries" },
  { id: 861, name: "Chicken Curry", price: 250, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (204).webp", category: "non-veg chicken curries" },
  { id: 862, name: "Andhra Chicken Curry", price: 260, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (205).webp", category: "non-veg chicken curries" },
  { id: 863, name: "Gongura Chicken Curry", price: 270, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (206).webp", category: "non-veg chicken curries" },
  { id: 864, name: "Chicken H0yderabadi", price: 250, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (207).webp", category: "non-veg chicken curries" },
  { id: 865, name: "Chicken Hundi", price: 260, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (208).webp", category: "non-veg chicken curries" },
  { id: 866, name: "Chicken Do Pyaz", price: 260, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (209).webp", category: "non-veg chicken curries" },
  { id: 867, name: "Chicken Rayalseema", price: 260, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (210).webp", category: "non-veg chicken curries" },
  { id: 868, name: "Chicken Patyala", price: 250, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (211).webp", category: "non-veg chicken curries" },
  { id: 869, name: "Chicken Punjabi", price: 250, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (212).webp", category: "non-veg chicken curries" },
  { id: 870, name: "Chicken Afghani", price: 250, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (213).webp", category: "non-veg chicken curries" },
  { id: 871, name: "Chicken Kolhapuri", price: 270, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (214).webp", category: "non-veg chicken curries" },
  { id: 872, name: "Chicken Tikka Masala", price: 280, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (215).webp", category: "non-veg chicken curries" },
  { id: 873, name: "Chicken Kaju Curry", price: 280, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (216).webp", category: "non-veg chicken curries" },
  { id: 874, name: "Chicken Tangadi Masala", price: 260, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (217).webp", category: "non-veg chicken curries" },
  { id: 875, name: "Methi Chicken", price: 250, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (218).webp", category: "non-veg chicken curries" },
  { id: 876, name: "Chicken Lajawab", price: 250, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (219).webp", category: "non-veg chicken curries" },
  { id: 877, name: "Chicken Mughlai", price: 270, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (220).webp", category: "non-veg chicken curries" },
  { id: 878, name: "Chicken Maharaja", price: 270, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (221).webp", category: "non-veg chicken curries" },
  { id: 879, name: "Chicken Singapore (Bone)", price: 260, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (222).webp", category: "non-veg chicken curries" },
  { id: 880, name: "Chicken Maharani", price: 260, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (223).webp", category: "non-veg chicken curries" },
  { id: 881, name: "Chicken Mandakini", price: 260, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (224).webp", category: "non-veg chicken curries" },
  { id: 882, name: "Natukodi Pulusu", price: 310, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (225).webp", category: "non-veg chicken curries" },
  { id: 883, name: "Natukodi Curry", price: 310, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (226).webp", category: "non-veg chicken curries" },

  //Mutton curries
  { id: 884, name: "Mutton Masala", price: 310, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (227).webp", category: "Mutton curries" },
  { id: 885, name: "Mutton Bawarchi", price: 310, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (228).webp", category: "Mutton curries" },
  { id: 886, name: "Mutton Nawabi", price: 310, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (229).webp", category: "Mutton curries" },
  { id: 887, name: "Kadai Mutton", price: 310, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (230).webp", category: "Mutton curries" },
  { id: 888, name: "Mutton Hyderabadi", price: 320, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (231).webp", category: "Mutton curries" },
  { id: 889, name: "Mutton Hundi", price: 320, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (232).webp", category: "Mutton curries" },
  { id: 890, name: "Mutton Do Pyaz", price: 320, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (233).webp", category: "Mutton curries" },
  { id: 891, name: "Mutton Rojan", price: 320, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (234).webp", category: "Mutton curries" },
  { id: 892, name: "Mutton Mughlai", price: 320, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (235).webp", category: "Mutton curries" },
  { id: 893, name: "Methi Mutton", price: 320, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (236).webp", category: "Mutton curries" },
  { id: 894, name: "Mutton Keema Curry", price: 340, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (237).webp", category: "Mutton curries" },
  { id: 895, name: "Andhra Mutton", price: 340, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (238).webp", category: "Mutton curries" },
  { id: 896, name: "Mutton Kolhapuri", price: 340, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (239).webp", category: "Mutton curries" },
  { id: 897, name: "Mutton Curry", price: 340, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (240).webp", category: "Mutton curries" },
  { id: 898, name: "Mutton Singapore", price: 340, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (241).webp", category: "Mutton curries" },
  { id: 899, name: "Gongura Mutton Curry", price: 340, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (242).webp", category: "Mutton curries" },

  //fish curries
  { id: 900, name: "Fish Curry", price: 270, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (243).webp", category: "fish curries" },
  { id: 901, name: "Fish Masala", price: 270, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (244).webp", category: "fish curries" },
  { id: 902, name: "Rayalaseema Fish Curry", price: 280, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (245).webp", category: "fish curries" },
  { id: 903, name: "Prawns Masala", price: 280, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (246).webp", category: "fish curries" },
  { id: 904, name: "Prawns Curry", price: 280, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (247).webp", category: "fish curries" },

  //NON VEG FRIED RICE
  { id: 905, name: "Chicken Fried Rice", price: 200, restid: 8, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "NON VEG FRIED RICE" },
  { id: 906, name: "Egg Fried Rice", price: 180, restid: 8, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "NON VEG FRIED RICE" },
  { id: 907, name: "Mix Non Veg Fried Rice", price: 210, restid: 8, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "NON VEG FRIED RICE" },
  { id: 908, name: "Chicken Schezwan Fried Rice", price: 210, restid: 8, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "NON VEG FRIED RICE" },

  //VEG FRIED RICE
  { id: 909, name: "Veg Fried Rice", price: 180, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "VEG FRIED RICE" },
  { id: 910, name: "Veg Gobi Fried Rice", price: 180, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "VEG FRIED RICE" },
  { id: 911, name: "Veg Mushroom Fried Rice", price: 180, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "VEG FRIED RICE" },
  { id: 912, name: "Paneer Fried Rice", price: 190, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "VEG FRIED RICE" },
  { id: 913, name: "Kaju Fried Rice", price: 200, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "VEG FRIED RICE" },
  { id: 914, name: "Veg Schezwan Fried Rice", price: 190, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "VEG FRIED RICE" },
  { id: 915, name: "Tomato Rice", price: 160, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "VEG FRIED RICE" },
  { id: 916, name: "Jeera Rice", price: 180, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "VEG FRIED RICE" },
  { id: 917, name: "Ghee Rice", price: 190, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "VEG FRIED RICE" },
  { id: 918, name: "Curd Rice", price: 100, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "VEG FRIED RICE" },
  { id: 919, name: "Plain Curd", price: 30, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "VEG FRIED RICE" },

  //ROTI'S
  { id: 920, name: "Tandoori Roti", price: 30, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "ROTI'S" },
  { id: 921, name: "Butter Roti", price: 40, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "ROTI'S" },
  { id: 922, name: "Plain Naan", price: 40, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "ROTI'S" },
  { id: 923, name: "Butter Naan", price: 45, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "ROTI'S" },
  { id: 924, name: "Tandoori Parota (1)", price: 35, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "ROTI'S" },
  { id: 925, name: "Aloo Parota", price: 60, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "ROTI'S" },
  { id: 926, name: "Rumali Roti", price: 40, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "ROTI'S" },
  { id: 927, name: "Lacha Parota", price: 40, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "ROTI'S" },
  { id: 928, name: "Kulcha", price: 40, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "ROTI'S" },
  { id: 929, name: "Masala Kulcha", price: 60, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "ROTI'S" },
  { id: 930, name: "Pudina Parota", price: 50, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "ROTI'S" },
  { id: 931, name: "Garlic Naan", price: 50, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "ROTI'S" },
  { id: 932, name: "Methi Roti", price: 45, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "ROTI'S" },
  { id: 933, name: "Cheese Naan", price: 60, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "ROTI'S" },
  { id: 934, name: "Butter Kulcha", price: 50, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "ROTI'S" },
  { id: 935, name: "Paneer Kulcha", price: 60, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "ROTI'S" },

  //VEG DUM BIRYANI
  { id: 936, name: "Veg Dum Biryani", price: 200, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "VEG DUM BIRYANI" },
  { id: 937, name: "Kaju Dom Biryani", price: 230, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "VEG DUM BIRYANI" },
  { id: 938, name: "Paneer Biryani", price: 220, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "VEG DUM BIRYANI" },
  { id: 939, name: "Mushroom Biryani", price: 200, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "VEG DUM BIRYANI" },
  { id: 940, name: "Veg Palav", price: 200, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "VEG DUM BIRYANI" },

  //BIRYANIS' NON VEG
  { id: 941, name: "PR Grand Spl Chicken Biryani", price: 310, restid: 8, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "BIRYANIS' NON VEG" },
  { id: 942, name: "Chicken Dum Biryani", price: 240, restid: 8, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "BIRYANIS' NON VEG" },
  { id: 943, name: "Chicken Lollipop Biryani", price: 300, restid: 8, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "BIRYANIS' NON VEG" },
  { id: 944, name: "Chicken Roast Biryani", price: 270, restid: 8, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "BIRYANIS' NON VEG" },
  { id: 945, name: "Mogalai Chicken Biryani", price: 300, restid: 8, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "BIRYANIS' NON VEG" },
  { id: 946, name: "Ulava Charu Chicken Biryani", price: 290, restid: 8, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "BIRYANIS' NON VEG" },
  { id: 947, name: "Gongura Chicken Biryani", price: 280, restid: 8, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "BIRYANIS' NON VEG" },
  { id: 948, name: "Biryani Rice", price: 170, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp", category: "BIRYANIS' NON VEG" },
  { id: 949, name: "PR Grand Spl Mutton Biryani", price: 360, restid: 8, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "BIRYANIS' NON VEG" },
  { id: 950, name: "Mutton Biryani", price: 320, restid: 8, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "BIRYANIS' NON VEG" },
  { id: 951, name: "Gongura Mutton Biryani", price: 340, restid: 8, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "BIRYANIS' NON VEG" },
  { id: 952, name: "Ulava Charu Mutton Biryani", price: 350, restid: 8, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "BIRYANIS' NON VEG" },
  { id: 953, name: "Mutton Keema Biryani", price: 330, restid: 8, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "BIRYANIS' NON VEG" },
  { id: 954, name: "Egg Biryani", price: 180, restid: 8, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "BIRYANIS' NON VEG" },
  { id: 955, name: "Fish Biryani", price: 280, restid: 8, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "BIRYANIS' NON VEG" },
  { id: 956, name: "Prawns Biryani", price: 280, restid: 8, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "BIRYANIS' NON VEG" },
  { id: 957, name: "Tangadi Biryani", price: 290, restid: 8, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "BIRYANIS' NON VEG" },
  { id: 958, name: "Tandoori Biryani", price: 300, restid: 8, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "BIRYANIS' NON VEG" },
  { id: 959, name: "Tikka Chicken Biryani", price: 300, restid: 8, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "BIRYANIS' NON VEG" },
  { id: 960, name: "Natu Kodi Biryani", price: 280, restid: 8, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "BIRYANIS' NON VEG" },
  { id: 961, name: "Kamju Biryani", price: 260, restid: 8, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "BIRYANIS' NON VEG" },
  { id: 962, name: "Potlam Chicken Biryani", price: 300, restid: 8, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "BIRYANIS' NON VEG" },

  //comboes and family packs
  { id: 963, name: "Chicken Biryani Family Pack", price: 800, restid: 8, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "comboes and family packs" },
  { id: 964, name: "Chicken Biryani Combo Pack", price: 1100, restid: 8, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "comboes and family packs" },
  { id: 965, name: "Mutton Biryani Family Pack", price: 1000, restid: 8, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "comboes and family packs" },
  { id: 966, name: "Mutton Biryani Combo Pack", price: 1480, restid: 8, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp", category: "comboes and family packs" }




]
